### ISSUE TITLE
why not work on nodemcu with sim800l wst reset after connecting gprs?

### ISSUE THREAD

**Issue by Adney** [vshymanskyy/TinyGSM#1]
Hi

**Comment by vshymanskyy** [comment]
Just committed a fix for that, but i didn't have a chance to check if it works - could you please check if it helps in your situation?

**Comment by Adney** [comment]
Thank you.
https://youtu.be/KrreU-3m1-I
Now it is working on mqtt nodemcu with Sim800l.
But in blynk , still not working. Just reboots wst reset nodemcu

**Comment by Adney** [comment]
arduino nano with sim800l - don't work blynk.

sketch loaded in the series is empty, nothing happens.

Test Diagnostics is ok, all working.
MQTT is work.

BLYNK is don't working.

**Comment by vshymanskyy** [comment]
What do you mean, don't work?

**Comment by Adney** [comment]
Nodemcu после загрузки скетча BLYNK, сразу начинает перезагружаться: wst reser.
Arduino NANO после загрузки скетча BLYNK - молчит. В сериал порту пусто, модуль SIM800 не пытается даже установить соединение.

Скетч MQTT клиет - работает.
А вот BLYNK не работает.

**Comment by vshymanskyy** [comment]
Fixed & tested on ESP8266

**Comment by Adney** [comment]
Thanks, now BLYNK is work!!!
