### ISSUE TITLE
SIM7XXX LTE modules support

### ISSUE THREAD

**Issue by tusharvb19** [vshymanskyy/TinyGSM#105]
Can we port the existing library to work with the LTE modules?
Thanks.

**Comment by tusharvb19** [comment]
Can we modify TinyGSM like this where the main adafruit library is modified!
https://github.com/botletics/NB-IoT-Shield

**Comment by vshymanskyy** [comment]
Yes you can. Pull Requests are welcome!

**Comment by tusharvb19** [comment]
I am beginner can anyone modify it and test it?
Thank you.

**Comment by vshymanskyy** [comment]
If someone is willing to donate a board, I can take a look at it..

**Comment by anthonyvage** [comment]
Let me know if i can send you a SIM7000 module

**Comment by finchamp** [comment]
I would also like to see support for SIM7000/C/E. If someone can get him a module, I'll put a bounty on it.

**Comment by finchamp** [comment]
This guy claims to have Hologram working with SIM7000?: https://github.com/botletics/SIM7000-LTE-Shield

**Comment by jhonoryza** [comment]
please add this support guys 👍 :)

**Comment by botletics** [comment]
I can send him a free shield kit.

**Comment by SRGDamia1** [comment]
Support for the SIM7000 was added courtesy of https://github.com/captFuture.

**Comment by anatom74** [comment]
This is only support for SIM7000. What about SIM75XX and SIM76XX?
