### ISSUE TITLE
AI-Thinker A6 + GPRS

### ISSUE THREAD

**Issue by martinlierschof** [vshymanskyy/TinyGSM#107]
Besides other issues, with my A6s, you should not call AT+CSTT. 
Calling CSTT results in that CIPSTART only works with IP and CIPSEND never sends anything actually to the server.

**Comment by vshymanskyy** [comment]
Which firmware version do you have?

**Comment by martinlierschof** [comment]
Trunk. I'll send a better and more detailed explanation later

**Comment by vshymanskyy** [comment]
Any updates?

**Comment by vshymanskyy** [comment]
Closing due to lack of interest
