### ISSUE TITLE
Which module do you suggest me? ( SIM8xx SSL/TLS)

### ISSUE THREAD

**Issue by adepalo** [vshymanskyy/TinyGSM#109]
Hi, 

I need a module which supports SSL/TLS (HTTPS), MQTT and GSM location service. I thought about SIM8xx, but, about SSL/TLS, only some device models or firmware revisions have this feature.
Which one I've to buy?
can you please send me a link? 
Also, which SIM8xx supports GPS/GNSS?
Regards
Andrea

**Comment by vshymanskyy** [comment]
https://gitter.im/tinygsm/Lobby
