### ISSUE TITLE
pass min and max to TinyGsmAutoBaud()

### ISSUE THREAD

**Issue by dmnc-net** [vshymanskyy/TinyGSM#110]
There are known limitations with high baud rates on SoftwareSerial so I'd like to limit maximum baud rate by calling i.e. `TinyGsmAutoBaud(SerialAT, 9600, 57600);`, but I'm getting error because just 1 argument is expected.
https://github.com/vshymanskyy/TinyGSM/blob/a51591ae9bf6feebbbad607ca79fbabcf067cd8a/src/TinyGsmCommon.h#L75

**Comment by vshymanskyy** [comment]
probably you just need to update the library to the latest version from master branch ... or wait for the next stable version.
