### ISSUE TITLE
'TinyGsm' has no member named 'isGprsConnected'

### ISSUE THREAD

**Issue by lathoub** [vshymanskyy/TinyGSM#114]
Hi

My code:
`
#define TINY_GSM_MODEM_SIM800
`
...
`
#include <TinyGsmClient.h>
`
`
TinyGsm modem(SerialAT);
`
...
`
 if (!modem.isGprsConnected())
  {
    modem.gprsConnect(apn, user, pass);
  }
`

I get the following compile error:

`
ProjectTiny:231: error: 'TinyGsm' has no member named 'isGprsConnected'
`

Yet `isGprsConnected` is defined in `TinyGsmClientSIM800.h`
Can someone see what I'm doing wrong?

Thanks

**Comment by vossie123** [comment]
I am having the same issue
'class TinyGsm' has no member named 'isGprsConnected'
also
'class TinyGsm' has no member named 'localIP'

**Comment by SRGDamia1** [comment]
I'm sorry @vossie123, I can't help you much without more detail.  Please open a new issues instead of commenting on a fairly old closed one.
