### ISSUE TITLE
UDP socket support

### ISSUE THREAD

**Issue by hpeterka** [vshymanskyy/TinyGSM#116]
Hello,
is there any reason why this great library doesn´t support UDP sockets? Thanks!

**Comment by SRGDamia1** [comment]
I think it's on the TO-DO list.

**Comment by vshymanskyy** [comment]
It is on TODO list

**Comment by jpmeijers** [comment]
I was wondering the same thing today when I realised that I will have to do an NTP query to get the time as it's not guaranteed that my Ublox modem gets the time from the network.

UDP in this library would allow us to use:
https://www.arduino.cc/en/Tutorial/UdpNtpClient

**Comment by SRGDamia1** [comment]
It's still on the to-do list.

**Comment by SunboX** [comment]
Is it still on the To-Do list?

**Comment by jpmeijers** [comment]
I can't remember exactly if I ended up implementing this myself or not. My code does: 
```
TinyGsmClient udpClient(modem, 0, UDP);
udpClient.connect(NTP_SERVER, NTP_PORT);
udpClient.write(packetBuffer, NTP_PACKET_SIZE);
while(i < NTP_PACKET_SIZE) {
    int c = udpClient.read();
    ....
}
udpClient.stop();
```

Using my SARA-G450 fork of the library, so it is possible that I implemented the UDP client for this specific modem:
https://github.com/jpmeijers/TinyGSM/blob/g450-relative-incl/src/TinyGsmClientSaraG450.h

**Comment by SunboX** [comment]
Thx, I will take a look. Commands might be a bit different for the SIM800 I'm using, but I guess I can figure that out. General library support would be really nice. :)

**Comment by SRGDamia1** [comment]
UDP is still on my "someday" list.  But unfortunately, it's still just "someday.."

**Comment by capedra** [comment]
@gonzabrusco 
Sure, why not?
![image](https://user-images.githubusercontent.com/412434/213910879-798c4867-813f-474d-b0c0-2d98aa8fb111.png)
