### ISSUE TITLE
Does it work with SIM868 module?

### ISSUE THREAD

**Issue by bkrajendra** [vshymanskyy/TinyGSM#126]
[Question]
Does it work with **Gsm/Gprs/Gnss/Bluetooth Hat For Raspberry Pi** SIM868 module?

[Module Link](https://www.waveshare.com/wiki/GSM/GPRS/GNSS_HAT)

**Comment by vshymanskyy** [comment]
It should.
Please don't use Issues for Questions. You have Gitter chat room. Thx!
