### ISSUE TITLE
SIM5360 modem support

### ISSUE THREAD

**Issue by OlexandrStepanov** [vshymanskyy/TinyGSM#129]
Hello @vshymanskyy,

As far as I see from the README, SIM5360 type of modem is not supported by this library yet.
Could you tell me, please, are there any plans to add support for SIM5360 in any future soon?
Many thanks.

With regards.

**Comment by vshymanskyy** [comment]
It is planned to add at some point, but unfortunately I don't have this hardware to test with. I'll contact you separately regarding hw questions.
