### ISSUE TITLE
lack of http test page for diagnostics

### ISSUE THREAD

**Issue by lswidere** [vshymanskyy/TinyGSM#134]
this 

const char server[] = "cdn.rawgit.com";
const char resource[] = "/vshymanskyy/tinygsm/master/extras/logo.txt";

returns HTTP 301 causing diagnostics example fail.

**Comment by vshymanskyy** [comment]
Thanks, I'll re-check!

**Comment by vshymanskyy** [comment]
Ok, I decided to bring up my own test server.

**Comment by vshymanskyy** [comment]
Should be resolved now (on master branch). Please reopen if happens again.
Thanks!
