### ISSUE TITLE
TinyGSM/examples/FileDownload/ memory issues on Nano

### ISSUE THREAD

**Issue by bionicbone** [vshymanskyy/TinyGSM#137]
Hi,

Great project so I thought I'd take the time to report this...

After trying for several hours trying to work  this out it appears to make this example work on a Nano with the SoftSerial and the M590 I needed lower the buffer line down to:

// Increase RX buffer
#define TINY_GSM_RX_BUFFER 800

Otherwise it just loops with waiting for network...fail which leads you to think it is a network issue :)

Kev

**Comment by vshymanskyy** [comment]
Thank. I think i need to address that in readme
