### ISSUE TITLE
update the MqttClient

### ISSUE THREAD

**Issue by muzmmilkhan** [vshymanskyy/TinyGSM#141]
sir please update the mqtt and include the username and password for mqtt  make it understandable
i want to connect to clodmqtt i.e https://www.cloudmqtt.com/ which is cloude based mosquitto so please update it
thank you

**Comment by vshymanskyy** [comment]
You can use any MQTT Client you want. What exactly library you're talking about?

**Comment by vshymanskyy** [comment]
Closing for now, as it has nothing to do with TinyGSM. Waiting for your replies

**Comment by vshymanskyy** [comment]
You can also post your question to PubSubClient

**Comment by vshymanskyy** [comment]
@muzmmilkhan check out this example:
https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_auth/mqtt_auth.ino
