### ISSUE TITLE
frequent call to mqtt.loop() function blocks the code

### ISSUE THREAD

**Issue by himanshu-hearthacker** [vshymanskyy/TinyGSM#142]
hello,
I am trying to connect with broker using sim808. I successfully managed to connect to mqtt broker using tinygsm library but I am facing some weird issue of code blocking. My code blocks after 2-3 hour of operation and it block at the starting of loop() function of pubsubclient library.
It would be great if you please give a clue where i could be wrong.

**Comment by kamrulroky** [comment]
I am facing the exact same issue with sim800, it works perfectly for few hours  but after that the program just freezes. really hoping for some suggestions here.
@himanshu-hearthacker  please let me know you have figured it out what exactly is causing the problem

**Comment by himanshu-hearthacker** [comment]
I have made a small change in my code. Call mqtt.loop() function in every 10 ms rather than frequently in loop() function of Arduino. I also incorporate serial.flush() before every mqtt.loop() call to ensure empty serial buffer before sending any request. May be this helps you.

**Comment by kamrulroky** [comment]
thanks @himanshu-hearthacker ,I have tried those you mentioned but still no luck.have you solved your problem by applying these?

**Comment by vshymanskyy** [comment]
I'm closing this, as you created another issue with similar symptoms, which is probably related: https://github.com/vshymanskyy/TinyGSM/issues/145

**Comment by himanshu-hearthacker** [comment]
my code stuck at _client->read() function in readByte() function in pubsubclient.cpp. Try to include timeout there.
