### ISSUE TITLE
code stuck at waitResponse() function

### ISSUE THREAD

**Issue by himanshu-hearthacker** [vshymanskyy/TinyGSM#144]
My code blocks infinitely at waitResponse() function after 4-5 hours of running loop() function of Arduino.  I I am updating signal strength every 30 second but after 4-5 hours of operation my code Stuck at waitResponse() function. I don't know how waitResponse() function works but my code blocks infinitely here. Hoping to get some useful suggestion here.

**Comment by vshymanskyy** [comment]
Please provide more info like the hardware you use, AT command log, etc. and reopen the issue
