### ISSUE TITLE
code stuck in getRegistrationStatus() function

### ISSUE THREAD

**Issue by himanshu-hearthacker** [vshymanskyy/TinyGSM#145]
My code blocks infinitely  after 4-5 hours of running loop() function of Arduino. I am updating signal strength every 30 second but after 4-5 hours of operation code blicks. In debug using Serial.print() statements i found that my code stuck  before the  waitResponse() function in the getRegistrationStatus() method.
I am using SIM 808 for GPRS/ GPS data. I am sending GPS data to server every 10th second and updating Signal strength every 30 second.  
This  case generally happens when I am not getting any ACK from past 30-40 seconds. I am checking if my device is registered with network or not using getRegistrationStatus() method before updating signal strength.

**Comment by vshymanskyy** [comment]
it looks like your modem stopped responding. This may be due to power issue, unreliable modem serial connection, interference, etc.
You should definitely try enabling AT commands output to your serial to see what the actual modem response is.

**Comment by vshymanskyy** [comment]
Was the issue resolved?
