### ISSUE TITLE
Library Crashing ESP32 If Ran On Core 0

### ISSUE THREAD

**Issue by DjordjeMandic** [vshymanskyy/TinyGSM#147]
If you use `xTaskCreatePinnedToCore(core0, "code0task", 1000, NULL, 1, &Core0Task, 0)` command for this library then make sure to set 1000 to 8192 otherwise cpu will crash with `Guru Meditation Error: Core  0 panic'ed (Unhandled debug exception)
Debug exception reason: Stack canary watchpoint triggered (code0task) `.
So proper command would look like: 
`xTaskCreatePinnedToCore(core0, "code0task", 8192, NULL, 1, &Core0Task, 0)`
I have no idea why this works but let it be. 
![cce2zhnwiaah0vj](https://user-images.githubusercontent.com/6750655/37811488-de0031dc-2e5a-11e8-952a-49155e389603.jpg)

**Comment by lg007** [comment]
Could you share with us your code? I would like to run theTinyGSM library on Core 0 of the ESP32.
