### ISSUE TITLE
A7 hanging on http.get(resource) using HttpClient Example

### ISSUE THREAD

**Issue by roja** [vshymanskyy/TinyGSM#148]
TinyGSM version: 0.3.2
Hardware: ESP8266 + A7

### Scenario, steps to reproduce
Using the example "HttpClient" using the A7 over ports 14,12 and the o2 network in the uk

### Expected result
Should download logo.txt sucessfully

### Actual result
Hangs when http.get(resource) is called.

**Comment by vshymanskyy** [comment]
Could you please provide the AT command log?

**Comment by AmrAlaa-exe** [comment]
Same issue,
------------
Performing HTTP GET request... AT+CIPCLOSE=255

+CME ERROR:53
AT+CIPSTART="TCP","156.209.63.76",2000

+CIPNUM:0

CONNECT OK

OK
AT+CIPSEND=0,3

>GET 
OK
AT+CIPSEND=0,1

>  
OK
AT+CIPSEND=0,7

>/api/a7
OK
AT+CIPSEND=0,9

> HTTP/1.1 
OK
AT+CIPSEND=0,2

>
 
OK
AT+CIPSEND=0,6

>Host:  
OK
AT+CIPSEND=0,13

>156.209.63.76 
OK
AT+CIPSEND=0,1

>: 
OK
AT+CIPSEND=0,4

>2000 
OK
AT+CIPSEND=0,2

>
 
OK
AT+CIPSEND=0,10

>User-Agent 
OK
AT+CIPSEND=0,2

>:  
OK
AT+CIPSEND=0,13

>Arduino/2.2.0 AT+CIPSEND=0,2

>
 AT+CIPSEND=0,10
AT+CIPSEND=0,2

>:  AT+CIPSEND=0,5
AT+CIPSEND=0,2

>
 AT+CIPSEND=0,2

> 
+TCPCLOSED:0

+CME ERROR:53
-3

**Comment by vshymanskyy** [comment]
@AmrAlaa-exe what hardware do you use?

**Comment by AmrAlaa-exe** [comment]
@vshymanskyy  ATmega32U4 combined with the A7 module.
https://goo.gl/SHVG9m

**Comment by vshymanskyy** [comment]
@roja any updates?

**Comment by vshymanskyy** [comment]
Closing this issue as no additional info provided
