### ISSUE TITLE
mqtt Client connection delay

### ISSUE THREAD

**Issue by sankaramp** [vshymanskyy/TinyGSM#149]
hello,
I'm using this library for MQTT Client and Broker communication..
my Problem is "taking much more time for connection (function:  mqttConnect(); ) and sometimes connection failed also.
I want to publish data to MQTT-Broker for every 10mins interval.

plz give me suggetions to solve this.

regards,
Sankar.

**Comment by vshymanskyy** [comment]
Closing as the issue is not well-documented. Please follow the issue template
