### ISSUE TITLE
make modemGetConnected public

### ISSUE THREAD

**Issue by mcr-ksh** [vshymanskyy/TinyGSM#156]
TinyGSM version: 0.3.3
Hardware: SIM800L, A6

can this function be public so the connection state can be queried?

Best,
MR

**Comment by vshymanskyy** [comment]
FYI, you should never use `modemGetConnected`.
You should use either `Client.connected()` or `modem.isGprsConnected()`. Or, in some rare cases, `modem.isNetworkConnected()`
