### ISSUE TITLE
Encrypted MQTT Connection with A6/A7

### ISSUE THREAD

**Issue by jcbrataas** [vshymanskyy/TinyGSM#16]
Hi,

Great work on TinyGSM, just tested with an AI Thinker A7. I started testing against my MQTT broker on port 8883 and it times out, tested with 1883 and that works fine. 

Cant find any information on the A7 or A6 about TLS/SSL support, do you know if its supported ?

**Comment by vshymanskyy** [comment]
AFAIK,  A7 and A6 do not have TLS/SSL.
