### ISSUE TITLE
POST Commands

### ISSUE THREAD

**Issue by MPsychoE** [vshymanskyy/TinyGSM#172]
TinyGSM version: 
Hardware: 
I am using sim900 board with arduino uno.
### Scenario, steps to reproduce

I want to send the data to my custom server of posttestserver. But there is no support that how can i do. Please help. 
I am using http.addHeader("Content-Type", "text/plain"); but it stucks
### Expected result

expected 200 but
### Actual result

I am getting 411 error code

**Comment by hubaksis** [comment]
Please provide the full code that sends data.
HTTP Status Code 411  means "Length Required", which means that you don't send "Content-Length" header.

**Comment by vshymanskyy** [comment]
Closing, as not related to TinyGSM
