### ISSUE TITLE
[A6] HTTP PUT

### ISSUE THREAD

**Issue by Setius2** [vshymanskyy/TinyGSM#176]
TinyGSM version: 0.3.5
Hardware: A6, Arduino UNO

### Scenario, steps to reproduce

I'm trying to send an HTTP PUT request and get a response from the Blynk server. 

### Expected result

I expect that the data will come to the server and the server will send a response. 

### Actual result

I see that after starting the board, only the data from the first PUT request gets to the server. The code following after the PUT is not processed.
I tried to analyze the problem and found that I fell into the trap of "while (!stream.available())".

file TinyGsmClientA6.h
function waitResponse
```
while (len--)
{
    while (!stream.available())
    { 
        TINY_GSM_YIELD();
    }
    sockets[mux]->rx.put(stream.read());
}
```

Using StreamDebugger, I found that the response from the server does not come fully (comes about 40 characters).
#100

**Comment by SRGDamia1** [comment]
I'm going to close this very old issue.  Please re-open it if you are still having trouble.
