### ISSUE TITLE
[Question] - what is the GF function

### ISSUE THREAD

**Issue by marabesi** [vshymanskyy/TinyGSM#178]
Hello guys,
First of all thank you for the lib, it is amazing.

Though, I was looking in to the source code and I saw this line (https://github.com/vshymanskyy/TinyGSM/blob/master/src/TinyGsmClientM590.h#L606)

````
sendAT(GF("+CIPSTATUS="), mux);
````

What the `GF` means before sending the AT command?

Is it something special?

**Comment by vshymanskyy** [comment]
GF is a macro that moves string constant to the Flash memory on some platforms, like AVR
