### ISSUE TITLE
Incorrect example sketch in TinyGSM/examples/more/Feather32U4FONA/Feather32U4FONA.ino

### ISSUE THREAD

**Issue by shanevanj** [vshymanskyy/TinyGSM#181]
TinyGSM version: current
Hardware: Feather32U4FONA

### Scenario, steps to reproduce
use example on Feather32U4FONA

### Expected result
Feather32U4FONA example usage of TinyGSM

### Actual result
Example is for MKR1400 which use different modem ublox vs SIM800

### AT command log
no relevant - wrong modem

**Comment by vshymanskyy** [comment]
The library does not provide any specific example for Feather32U4FONA. Where did you get it from?

**Comment by SRGDamia1** [comment]
I'm going to close this very old issue.  Please re-open it if you are still having trouble.
