### ISSUE TITLE
400 Bad request when using example

### ISSUE THREAD

**Issue by wimrutgeerts** [vshymanskyy/TinyGSM#191]
TinyGSM version: 0.3.5
Hardware: TINY_GSM_MODEM_SIM808  AND ESP8266

### Scenario, steps to reproduce
Run the example called HttpClient

### Expected result
gets the tiny gsm logo from the server

### Actual result
400 bad request is returned.

### AT command log
Initializing modem...
AT

OK
AT+CLTS=1

OK
AT&W

OK
AT+CFUN=0

+CPIN: NOT READY

OK
AT+CFUN=1,1

OK
AT

OK
AT&FZ
ATE0
ATE0

OK
AT+CPIN?

+CPIN: READY

OK
ATI

SIM808 R14.18

OK
Modem: SIM808 R14.18
Waiting for network...AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,2

OK
AT+CREG?

+CREG: 0,1

OK
 OK
Connecting to IEW.BEAT+CIPSHUT

SHUT OK
AT+CGATT=0

OK
AT+SAPBR=3,1,"Contype","GPRS"

OK
AT+SAPBR=3,1,"APN","IEW.BE"

OK
AT+CGDCONT=1,"IP","IEW.BE"

OK
AT+CGACT=1,1

OK
AT+SAPBR=1,1

OK
AT+SAPBR=2,1

+SAPBR: 1,1,"10.219.77.170"

OK
AT+CGATT=1

OK
AT+CIPMUX=1

OK
AT+CIPQSEND=1

OK
AT+CIPRXGET=1

OK
AT+CSTT="IEW.BE","",""

OK
AT+CIICR

OK
AT+CIFSR;E0

10.219.77.170

OK
AT+CDNSCFG="8.8.8.8","8.8.4.4"

OK
 OK
Performing HTTP GET request... AT+CIPCLOSE=1

ERROR
AT+CIPSSL=0

ERROR
AT+CIPSTART=1,"TCP","http://www.vsh.pp.ua",80

OK

1, CONNECT OK
AT+CIPSEND=1,3

>GET
DATA ACCEPT:1,3
AT+CIPSEND=1,1

> 
DATA ACCEPT:1,1
AT+CIPSEND=1,17

>/TinyGSM/logo.txt
DATA ACCEPT:1,17
AT+CIPSEND=1,9

> HTTP/1.1
DATA ACCEPT:1,9
AT+CIPSEND=1,2

>

DATA ACCEPT:1,2
AT+CIPSEND=1,6

>Host: 
DATA ACCEPT:1,6
AT+CIPSEND=1,20

>http://www.vsh.pp.ua
DATA ACCEPT:1,20
AT+CIPSEND=1,2

AT+CIPSEND=1,10

ERROR
AT+CIPSEND=1,2

ERROR
AT+CIPSEND=1,13

ERROR
AT+CIPSEND=1,2

ERROR
AT+CIPSEND=1,10

ERROR
AT+CIPSEND=1,2

ERROR
AT+CIPSEND=1,5

ERROR
AT+CIPSEND=1,2

ERROR
AT+CIPSEND=1,2

ERROR
AT+CIPRXGET=4,1

+CIPRXGET: 4,1,343

OK
AT+CIPRXGET=2,1,63

+CIPRXGET: 2,1,63,280
HTTP/1.1 400 Bad Request
Server: nginx/1.10.3 (Ubuntu)
Date: 
OK
400
AT+CIPRXGET=2,1,63

+CIPRXGET: 2,1,63,217
Fri, 10 Aug 2018 14:15:02 GMT
Content-Type: text/html
Content
OK
AT+CIPRXGET=2,1,63

+CIPRXGET: 2,1,63,154
-Length: 182
Connection: close

<html>
<head><title>400 Bad
OK
Content length is: 182
AT+CIPRXGET=2,1,63

+CIPRXGET: 2,1,63,91
 Request</title></head>
<body bgcolor="white">
<center><h1>40
OK
AT+CIPRXGET=2,1,63

+CIPRXGET: 2,1,63,28
0 Bad Request</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)<
OK
AT+CIPRXGET=2,1,63

+CIPRXGET: 2,1,28,0
/center>
</body>
</html>

OK
Response:
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

Body length is: 182
AT+CIPCLOSE=1

1, CLOSE OK
Server disconnected
AT+CIPSHUT

SHUT OK
AT+CGATT=0

+SAPBR 1: DEACT

OK
GPRS disconnected

**Comment by vshymanskyy** [comment]
Probably hardware issue, or unreliable serial connection to the module.
