### ISSUE TITLE
A6 module, resets but no data

### ISSUE THREAD

**Issue by 9H1LO** [vshymanskyy/TinyGSM#196]
Latest lib version

i can "hear" the radio tx on nearby pc speakers on power up
sim has valid data subs
module is init fine, connects to apn, but when trying to start actual tcp session nothing happens and i don't "hear" any transmission, testing with included examples, mainly httpclient and mqttclient

this is what i get in term

Initializing modem...
Modem: Ai Thinker Co.LTD A6  V03.06.20171127R
Waiting for network... OK
Connecting to internet OK
Connecting to vsh.pp.ua fail
Waiting for network... OK
Connecting to internet OK
Connecting to vsh.pp.ua fail
Waiting for network... OK
Connecting to internet OK
Connecting to vsh.pp.ua

**Comment by vshymanskyy** [comment]
Closing, as no AT command log is provided
