### ISSUE TITLE
[UBLOX] .init() function improperly defined

### ISSUE THREAD

**Issue by qcabrol** [vshymanskyy/TinyGSM#199]
Issue observed with Modem Model Ublox SARA-G350 on UART port using latest version of **src\TinyGsmClientUBLOX.h**

call to _modem.restart()_ always returns a boolean "FALSE" if no pin was provided and thus be a blocking condition in typical test cases where an "_if(modem.restart()){ ... }_" or "_if(modem.init()){ ... }_" is called without 'pin' argument.

This is counter to the _restart()_ definition that do not take a 'pin' argument as input and calls _.init()_ as empty. _.init()_ was written with a default 'pin=NULL' argument and as such, a SIM_LOCKED status shall be considered as a valid return, same as SIM_READY.

**Suggestion**

Replace in _.init()_ for src\TinyGsmClientUBLOX.h
`return (getSimStatus() == SIM_READY);`

by
`    ret = getSimStatus();
    return (ret == SIM_READY  || ret == SIM_LOCKED);`

**OR**
Make _.init()_ be of type uint8_t and return directly the sim status

**OR**
Change _.restart()_ and _.init()_ so they always require a non empty 'pin' argument

I have a personal preference for the first option that keep things more consistent. A restart call shall not need the pin to be provided.

**Comment by dansass** [comment]
Hi qcabrol
I have the sparkfun 4g shield and i am having a hard time getting it connected to blynk...

 im having trouble getting this shield connected to blynk. I uploaded and successfully connected the shield to hologram using the 00_Register_Operator sketch. On tinyGSM wiki it says that my modem is supported. When i enable blynk debug this is what pops up on my serial monitor

Initializing modem...
[8005] ### Unhandled: Manufacturer: u-blox
Model: SARA-R410M-02B
Revision: L0.0.00.00.05.06 [Feb 03 2018 13:00:41
V
M:55963
O
Modem:
[8083]

/ _ )/ /_ _____ / /__
/ _ / / // / _ / '/
///, /////
/__/ v0.6.1 on Arduino Uno

[8242] Modem init...
[8412] ### Modem: u-blox SARA-R410M-02B
[8550] Connecting to network...
[8659] Network: 302 720 Hologram
[8660] Connecting to hologram ...
[8744] ### Unhandled: Operation not allowed
[8810] Connecting to blynk-cloud.com:80
[8888] ### Unhandled: Operation not allowed
[13794] Connecting to blynk-cloud.com:80
[13873] ### Unhandled: Operation not allowed

Have u had any luck getting the thing connected??

Thanks, Daniel
