### ISSUE TITLE
Automatic reconnection

### ISSUE THREAD

**Issue by Anydy** [vshymanskyy/TinyGSM#20]
Is it possible to automatically restore GPRS connection of the modem in case of network or power loss?
If so, how to implement it?

**Comment by vshymanskyy** [comment]
You can restart your modem and reinit it for sure...

**Comment by vshymanskyy** [comment]
Did you solve your problem?

**Comment by Anydy** [comment]
I inserted a piece of code from the Setop into the LOOP
It is right? Or it is necessary as that on another?
So it reconnects when there is a power failure.
`void loop() {  
 if (mqtt.connected()) {
    mqtt.loop();
  } else {     
    // Reconnect every 10 seconds
    unsigned long t = millis();
    if (t - lastReconnectAttempt > 10000L) {
      lastReconnectAttempt = t;
     }
        if (mqttConnect()) {
        lastReconnectAttempt = 0;
          }
else if (!modem.gprsConnect(apn, user, pass)) {
       while (true);
}
    }
  }`

**Comment by vshymanskyy** [comment]
Hi, so did you solve the problem completely? Are there any other problems?

**Comment by vshymanskyy** [comment]
Closing due to lack of interest
