### ISSUE TITLE
SIM808 and Atmega328 - HttpClient vs WebClient

### ISSUE THREAD

**Issue by ostium** [vshymanskyy/TinyGSM#200]
Hello,

I need to read a webpage [http://www.iforce2d.net/test.php](url) using the example HttpClient. I want to do this in a loop way, and every 5s, download the page content.

The example, only do this one time. How can I change de example to do this in loop?
What is the best solution: HttpClient or WebClient?

Thanks for your help.
Greetings

**Comment by vshymanskyy** [comment]
Closing as this is not an issue. You should learn general Arduino programming basics.
