### ISSUE TITLE
Maximum MQTT Packet size ?

### ISSUE THREAD

**Issue by rajibgupta** [vshymanskyy/TinyGSM#202]
What is the maximum MQTT packet size allowed for a arduino-SIM800 setup  ?
How do I figure that out ?

**Comment by vshymanskyy** [comment]
closing as not related to TinyGSM

**Comment by arihantdaga** [comment]
@rajibgupta Maximum packet size for mqtt is defined in the pubsub client(I am assuming you are using pubSub Client library).By default its defined as 128 Bytes. You can write in your own code before including pubsubclient "#define MQTT_MAX_PACKET_SIZE  {Whatever size u want}".
