### ISSUE TITLE
[SIM900/SIM800] ERROR LOOP after a short time

### ISSUE THREAD

**Issue by laserfreak1111** [vshymanskyy/TinyGSM#21]
I have a SIM900 connected to an arduino uno (Software Serial)  running the MQTT example.
I publish a message every 10 seconds. 
After about 3-5 Minutes the sketch will end up in a loop.
This also happens if i use Hardware Serial for the SIM900.
Can it be a bad serial connection (i´m using 9600 baud)? (Noise because of the GSM Module).
Or is there something wrong with the software.

Attached is a Debug log of the communication and the sktech

[testgsm2sktech.txt](https://github.com/vshymanskyy/TinyGSM/files/881055/testgsm2sktech.txt)

[debug.txt](https://github.com/vshymanskyy/TinyGSM/files/881052/debug.txt)

**Comment by vshymanskyy** [comment]
Did you solve your issue?

**Comment by laserfreak1111** [comment]
not yet. Maybe a bad communication between my atmega2560/ mega328p and the SIM900 / A6 . But i cant do more then connect RX to TX and TX to RX. I also hooked up a logic analyzer. But everything looks fine. It just looses the connection and keeps looping with that error :(.

Do you have any ideas ?

**Comment by laserfreak1111** [comment]
Really ? . Ok i will try... I thought lower is better

**Comment by holgerkoch** [comment]
But why it works with higher baudrate?
I think, this is not a definitive solution. Only the probability that it works will be better.

Best regards

Holger

**Comment by gcardo** [comment]
i have same problem. infinit loop
arduino send "AT+CIPSTART=1" to sim800 and he responds "ERROR"

**Comment by vshymanskyy** [comment]
could you try if solutions from https://github.com/vshymanskyy/TinyGSM/issues/30 work for you?

**Comment by FabianInostroza** [comment]
This could be related with the issue #62  I submitted

**Comment by vshymanskyy** [comment]
Please reopen if this still happens on master branch. Thank you!
