### ISSUE TITLE
A6 Module V03.05 in MQTT 

### ISSUE THREAD

**Issue by cfvelez** [vshymanskyy/TinyGSM#210]
Hello, Do you know because the A6 gsm module with version V03.05 doesn't work with protocol MQTT and I get a error -2 MQTT_CONNECT_FAILED the network connection failed. I don't have this problem with the V03.02 version or A7 module and all works fine!. does anybody have idea how I can fix it in v03.05 in A6 gsm module?. I would appreciate any help. Thank you

**Comment by SRGDamia1** [comment]
The A6 is nearly identical between those tags.  Can you check which commits work and don't?

**Comment by cfvelez** [comment]
The CIPSTART command doestn´t work in V03.05, the response is never received.

**Comment by SRGDamia1** [comment]
I'm going to close this older issue.  Please re-open it if you're still having problems.
