### ISSUE TITLE
TinyGSM Sleep mode?

### ISSUE THREAD

**Issue by Bambofy** [vshymanskyy/TinyGSM#218]
Hi,

Is there a way to put the SIM800L into a low power sleep mode?

**Comment by SRGDamia1** [comment]
You can use the radioOff() function, which uses AT+CFUN=0 to put the module in reduced functionality or the powerOff() function which uses AT+CPOWD=1 to power it down.  To use powerOff() you need to have connection to the PWRKEY pin to turn it back on.  The SIM800 hardware integration guide has a log of information about the various power modes.
