### ISSUE TITLE
Arduino sim800a error using WebClient here

### ISSUE THREAD

**Issue by bbhxwl** [vshymanskyy/TinyGSM#22]
There is an error, return to fail, what is the general cause of

if (!modem.gprsConnect(apn, user, pass)) {
		Serial.println(" fail");
		delay(10000);
		return;
	}

**Comment by vshymanskyy** [comment]
Sorry, it's a very broad question - please check the available documentation for your module, enable debug of AT commands, etc. you need to specify exactly what did you check and what are console outputs, etc.

**Comment by vshymanskyy** [comment]
BTW, did you solve your issue?

**Comment by bbhxwl** [comment]
Solved, the use of arduino can, but esp8266 can not

**Comment by vshymanskyy** [comment]
Hm, strange
