### ISSUE TITLE
Can`t compile for ESP8266 (Nodemcu) as main board

### ISSUE THREAD

**Issue by saloid** [vshymanskyy/TinyGSM#220]
TinyGSM version: 0.3.5
ESP SDK: actual git clone from https://github.com/esp8266/Arduino

Hardware: Main board is ESP8266 (Nodemcu) with SIM800 connected to it.

### Scenario, steps to reproduce
Try to compile any example sketch with TinyGsmClient for Nodemcu board

### Expected result
Compilation success
### Actual result
Compilation error:
```
WebClient:66:17: error: cannot declare variable 'client' to be of abstract type 'TinyGsmSim800::GsmClient'

   TinyGsmClient client(modem);

                 ^

In file included from C:\Users\Dmytro\Documents\Arduino\libraries\TinyGSM\src/TinyGsmClient.h:22:0,

                 from C:\Users\Dmytro\AppData\Local\Temp\arduino_modified_sketch_886307\WebClient.ino:25:

C:\Users\Dmytro\Documents\Arduino\libraries\TinyGSM\src/TinyGsmClientSIM800.h:53:7: note:   because the following virtual functions are pure within 'TinyGsmSim800::GsmClient':

 class GsmClient : public Client

       ^

In file included from C:\Users\Dmytro\Documents\Arduino\libraries\TinyGSM\src/TinyGsmCommon.h:25:0,

                 from C:\Users\Dmytro\Documents\Arduino\libraries\TinyGSM\src/TinyGsmClientSIM800.h:21,

                 from C:\Users\Dmytro\Documents\Arduino\libraries\TinyGSM\src/TinyGsmClient.h:22,

                 from C:\Users\Dmytro\AppData\Local\Temp\arduino_modified_sketch_886307\WebClient.ino:25:

C:\Users\Dmytro\Documents\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Client.h:37:22: note: 	virtual bool Client::flush(unsigned int)

         virtual bool flush(unsigned int maxWaitMs = 0) = 0;

                      ^

C:\Users\Dmytro\Documents\Arduino\hardware\esp8266com\esp8266\cores\esp8266/Client.h:38:22: note: 	virtual bool Client::stop(unsigned int)

         virtual bool stop(unsigned int maxWaitMs = 0) = 0;

                      ^
```

**Comment by saloid** [comment]
Fixed it here: #221

**Comment by vshymanskyy** [comment]
I think this is an issue, introduced in ESP8266 core 2.5.0.
Need to investigate it further

**Comment by laxman-spidey** [comment]
I'm facing the same issue, is this solved yet? Does it work if i downgrade ESP8266 core to <2.5.0

**Comment by saloid** [comment]
Yes, look at my fix at the top

**Comment by SRGDamia1** [comment]
I think the correct solution will be to wait for the ESP8266 core to fix the extra virtual functions it introduced:
https://github.com/esp8266/Arduino/issues/5749

**Comment by emi1988** [comment]
> I'm facing the same issue, is this solved yet? Does it work if i downgrade ESP8266 core to <2.5.0

Yes, for me it works if I downgrade the ESP8266 core to Version 2.4.2

**Comment by d-a-v** [comment]
esp8266/Arduino#5969 adresses it

**Comment by hardmax** [comment]
Hi, the same problem with ESP32, I have to downgrade to 1.0.1 to works...

**Comment by SRGDamia1** [comment]
The compiler problems with the ESP32 and ESP8266 should now be fixed.
