### ISSUE TITLE
sim800L struck in Waitfornetwork();

### ISSUE THREAD

**Issue by yogeshwaran774** [vshymanskyy/TinyGSM#222]
i am using sim800L module and used AT commands to check the module is working are not through serial. sim detected and network registered +CREG (0,1) with full functionality mode and then i tried gprs connect AT+CGATT= 1 returns OK and then i tried AT+CMGF=1 to read messages. The problem is if upload tinygsm all function example code the program is returning after waitfornetwork.

But network is fine then also its keep on restarting. What could be the reason?

**Comment by sdrshnptl** [comment]
Try reducing baud rate to 9600 from auto baud.
default 115200 or 57600 may have noise.

**Comment by SRGDamia1** [comment]
I'm going to close this older issue.  Please re-open it if you're still having problems.
