### ISSUE TITLE
Azure IoT HUB

### ISSUE THREAD

**Issue by pedrofelipest** [vshymanskyy/TinyGSM#223]
Hello, is it possible to communicate with the azure iot-hub?

**Comment by vshymanskyy** [comment]
Probably the same answer as here: https://github.com/vshymanskyy/TinyGSM/issues/136

**Comment by AltusBaard** [comment]
> Hello, is it possible to communicate with the azure iot-hub?

Did you have any luck in getting it to work for Azure?
