### ISSUE TITLE
Dragino NB-IoT

### ISSUE THREAD

**Issue by facetime88** [vshymanskyy/TinyGSM#230]
Is this support with Dragino NB-IoT board with Quectel BG96?

**Comment by SRGDamia1** [comment]
It should, just use ```#define TINY_GSM_MODEM_BG96```

**Comment by facetime88** [comment]
Thanks for the info..! 
Is it support for board made by STMicrocontroller? I am thinking to switch to STM32F103C series.

**Comment by SRGDamia1** [comment]
It should work on the STM series; I haven't tried it personally though.
