### ISSUE TITLE
SIM 800L - HTTPS

### ISSUE THREAD

**Issue by potos3131** [vshymanskyy/TinyGSM#235]
Hi ! 
I've a SIM800L and i'd like to test SSL functionnalities (retrieve https data)
It's not easy as is seems ... is there anyone who has tested it ??
Do y ou have some test code ? The HTTPS code included in the example directory doesn't run...meanwhile the HTTP example is OK ... 

My firmware => **1418B05SIM800L24**

Many many thanks !

**Comment by vshymanskyy** [comment]
Not all firmware versions support SSL

**Comment by amotl** [comment]
Dear @potos3131,

while investigating SSL issues with **older** firmware revisions [1], we are able to confirm the very firmware revision you referenced above actually **does** support SSL.

Cheers,
Andreas.

[1] https://community.hiveeyes.org/t/unlocking-and-improving-the-pythings-sim800-gprs-module-for-micropython/2978/9

**Comment by SRGDamia1** [comment]
In reporting SSL support, TinyGSM just asks the SIM800 if it supports it (AT+CIPSSL=?). I'd never thought to truth-check that response. When attempting to *use* SSL, we try to set the SSL before opening the connection (AT+CIPSSL=1) whether or not we know it's supported and continue with the connection based on that response. As for any s

**Comment by amotl** [comment]
Dear Sara,

we have been able to confirm `AT+CIPSSL` responds with `ERROR` [1]
```
at+cipssl=?
ERROR
```
on `SIM800 R13.08`. Upgrading from firmware revision `1308B08SIM800L16` to `1308B09SIM800L16` (please note `B08` vs. `B09` here) by using the firmware image from [2] did not change that situation. So, we assume SSL support will only be available through the R14 release series.

Builds from the R14.18 release series are only published for the SIM800C and the SIM800F modules [3,4] and we are hesitant to put them on a SIM800L module.

Maybe you or @vshymanskyy would know if that would be safe or where to acquire appropriate firmware images for the SIM800L modules?

With kind regards,
Andreas.

[1] https://community.hiveeyes.org/t/unlocking-and-improving-the-pythings-sim800-gprs-module-for-micropython/2978/34
[2] https://simcom.ee/documents/?dir=SIM800
[3] https://simcom.ee/documents/?dir=SIM800F
[4] https://simcom.ee/documents/?dir=SIM800C
