### ISSUE TITLE
Stuck on "performing GET request"

### ISSUE THREAD

**Issue by Bambofy** [vshymanskyy/TinyGSM#237]
TinyGSM version: latest
Hardware: Ai Thinker Co.LTD A6  V03.03.20161229019H03, Arduino Mega

### Scenario, steps to reproduce
Running the sample HttpClient code.

### Expected result
Expecting to see the output of the given web address.

### Actual result
What actually happens is that the code reaches "Performing HTTP GET request..." and then freezes.

### AT command log

> 
> Initializing modem...
> 21:09:28.815 -> AT
> 
> 21:09:28.883 -> OK
> AT+RST=1
> AT
> 21:09:31.966 -> AT
> AT
> AT
> AT
> AT
> AT
> AT
> AT
> AT
> AT
> 21:09:34.980 -> AT
> 21:09:35.014 -> AT
> 21:09:35.014 -> AT
> 21:09:35.014 -> AT
> 21:09:35.014 -> AT
> 21:09:35.014 -> AT
> 21:09:35.014 -> AT
> 21:09:35.014 -> AT
> 21:09:35.014 -> AT
> 21:09:35.014 -> AT
> 21:09:35.014 -> AT
> 21:09:35.014 -> 
> 21:09:35.014 -> OK
> AT&FZE0
> AT&FZE0
> 
> 21:09:35.182 -> OK
> 21:09:35.182 -> AT+CMEE=0
> 
> 21:09:35.217 -> OK
> 21:09:35.217 -> AT+CMER=3,0,0,2
> 
> 21:09:35.284 -> OK
> 21:09:35.284 -> AT+CPIN?
> 
> 21:09:35.352 -> ERROR
> AT+CPIN?
> 
> 21:09:36.401 -> ERROR
> AT+CPIN?
> 
> 21:09:37.458 -> ERROR
> AT+CPIN?
> 21:09:38.470 -> 
> 21:09:38.470 -> ^CINIT: 1, 0, 0
> 21:09:38.470 -> 
> 21:09:38.470 -> ^CINIT: 2, 32, 41891
> 
> 21:09:38.603 -> +CPIN:READY
> 21:09:38.603 -> 
> 21:09:38.603 -> OK
> 21:09:38.603 -> ATI
> 21:09:38.670 -> Ai Thinker Co.LTD
> 21:09:38.670 -> A6 
> 21:09:38.670 -> V03.03.20161229019H03
> 21:09:38.670 -> 
> 21:09:38.670 -> OK
> 21:09:38.670 -> Modem: Ai Thinker Co.LTD A6  V03.03.20161229019H03
> 21:09:38.703 -> Waiting for network...AT+CREG?
> 21:09:38.738 -> +CREG: 1,10
> 21:09:38.738 -> 
> 21:09:38.738 -> OK
> AT+CREG?
> 
> 21:09:39.078 -> +CREG: 1,10
> 21:09:39.112 -> 
> 21:09:39.112 -> OK
> AT+CREG?
> 21:09:39.351 -> 
> 21:09:39.351 -> ^CINIT: 8, 2048, 1
> 21:09:39.351 -> 
> 21:09:39.351 -> ^CINIT: 16, 0, 1638410
> 
> 21:09:39.419 -> ^CINIT: 32, 0, 0
> 21:09:39.419 -> 
> 21:09:39.419 -> +CREG: 0
> 21:09:39.419 -> 
> 21:09:39.419 -> +CREG: 1,10
> 21:09:39.419 -> 
> 21:09:39.419 -> OK
> AT+CREG?
> 
> 21:09:39.720 -> +CREG: 1,10
> 21:09:39.720 -> 
> 21:09:39.720 -> OK
> AT+CREG?
> 
> 21:09:40.026 -> +CIEV: "SMSFULL",0
> 21:09:40.026 -> 
> 21:09:40.026 -> +CIEV: "MESSAGE",0
> 21:09:40.026 -> 
> 21:09:40.026 -> +CREG: 1,10
> 21:09:40.026 -> 
> 21:09:40.026 -> OK
> AT+CREG?
> 
> 21:09:40.361 -> +CREG: 1,10
> 21:09:40.361 -> 
> 21:09:40.361 -> OK
> AT+CREG?
> 
> 21:09:40.666 -> +CREG: 1,10
> 21:09:40.666 -> 
> 21:09:40.666 -> OK
> AT+CREG?
> 21:09:40.903 -> 
> 21:09:40.903 -> +CTZV:19/01/26,21:09:39,00
> 
> 21:09:40.970 -> +CREG: 1,10
> 21:09:40.970 -> 
> 21:09:40.970 -> OK
> AT+CREG?
> 
> 21:09:41.276 -> +CREG: 1,10
> 21:09:41.276 -> 
> 21:09:41.276 -> OK
> AT+CREG?
> 
> 21:09:41.612 -> +CIEV: service,  1
> 21:09:41.612 -> +CIEV: roam, 0
> 21:09:41.612 -> 
> 21:09:41.612 -> +CREG: 1
> 21:09:41.612 -> 
> 21:09:41.612 -> +CREG: 1,1
> 21:09:41.612 -> 
> 21:09:41.612 -> OK
> 21:09:41.612 ->  OK
> 21:09:41.612 -> Connecting to giffgaff.comAT+CIPSHUT
> 
> 21:09:41.679 -> ERROR
> 21:09:41.679 -> AT+CGATT=1
> 
> 21:09:46.062 -> OK
> 21:09:46.062 -> AT+CGDCONT=1,"IP","giffgaff.com"
> 
> 21:09:46.129 -> OK
> 21:09:46.129 -> AT+CSTT="giffgaff.com","",""
> 
> 21:09:46.195 -> OK
> 21:09:46.195 -> AT+CGACT=1,1
> 
> 21:09:46.971 -> OK
> 21:09:46.971 -> AT+CIPMUX=1
> 
> 21:09:47.038 -> OK
> 21:09:47.038 ->  OK
> 21:09:47.038 -> Performing HTTP GET request... AT+CIPCLOSE=255
> 
> 21:09:47.073 -> ERROR
> 21:09:47.073 -> AT+CIPSTART="TCP","vsh.pp.ua",80
> 
> 21:09:49.378 -> +CIPNUM:0
> 21:09:49.378 -> 
> 21:09:49.378 -> CONNECT OK
> 21:09:49.378 -> 
> 21:09:49.378 -> OK
> 21:09:49.378 -> AT+CIPSEND=0,3
> 
> 21:09:49.444 -> >GET 
> 21:09:49.814 -> OK
> 21:09:49.814 -> AT+CIPSEND=0,1
> 
> 21:09:49.882 -> >  
> 21:09:50.152 -> OK
> 21:09:50.152 -> AT+CIPSEND=0,17
> 
> 21:09:50.220 -> >/TinyGSM/logo.txt 
> 21:09:50.523 -> OK
> 21:09:50.523 -> AT+CIPSEND=0,9
> 
> 21:09:50.591 -> > HTTP/1.1 
> 21:09:50.830 -> OK
> 21:09:50.830 -> AT+CIPSEND=0,2
> 
> 21:09:50.897 -> >
> 21:09:50.897 ->  
> 21:09:51.167 -> OK
> 21:09:51.167 -> AT+CIPSEND=0,6
> 
> 21:09:51.235 -> >Host:  
> 21:09:51.472 -> OK
> 21:09:51.472 -> AT+CIPSEND=0,9
> 
> 21:09:51.541 -> >vsh.pp.ua 
> 21:09:51.809 -> OK
> 21:09:51.809 -> AT+CIPSEND=0,2
> 
> 21:09:51.877 -> >
> 21:09:51.877 ->  
> 21:09:52.149 -> OK
> 21:09:52.149 -> AT+CIPSEND=0,10
> 
> 21:09:52.215 -> >User-Agent 
> 21:09:52.452 -> OK
> 21:09:52.452 -> AT+CIPSEND=0,2
> 
> 21:09:52.519 -> >:  
> 21:09:52.754 -> OK
> 21:09:52.754 -> AT+CIPSEND=0,13
> 
> 21:09:52.821 -> >Arduino/2.2.0 
> 21:09:53.062 -> OK
> 21:09:53.062 -> AT+CIPSEND=0,2
> 
> 21:09:53.130 -> >
> 21:09:53.130 ->  
> 21:09:53.368 -> OK
> 21:09:53.368 -> AT+CIPSEND=0,10
> 
> 21:09:53.436 -> >Connection 
> 21:09:53.672 -> OK
> 21:09:53.672 -> AT+CIPSEND=0,2
> 
> 21:09:53.740 -> >:  
> 21:09:53.976 -> OK
> 21:09:53.976 -> AT+CIPSEND=0,5
> 
> 21:09:54.011 -> >close 
> 21:09:54.246 -> OK
> 21:09:54.246 -> AT+CIPSEND=0,2
> 
> 21:09:54.314 -> >
> 21:09:54.314 ->  
> 21:09:54.552 -> OK
> 21:09:54.552 -> AT+CIPSEND=0,2
> 
> 21:09:54.621 -> >
> 21:09:54.621 ->  
> 21:09:54.859 -> OK
> 
> 21:09:55.872 -> +CIPRCV:0,633,HTTP/1.1 200 OK
> 21:09:55.872 -> Server: nginx/1.10.3 (Ubuntu)
> 
> 21:10:07.412 -> +TCPCLOSED:0
> 
> 21:10:08.156 -> OK

**Comment by SRGDamia1** [comment]
Is this still an issue?  I'm going to close this as it's quite old.  Please re-open it if you're still having problems.
