### ISSUE TITLE
AT+CMGF=1

### ISSUE THREAD

**Issue by friistf** [vshymanskyy/TinyGSM#242]
<Hi,
I am using Goouuu Tech IOT-GA6.
I have issued the following commands:

Command             Reply
----------------------------------
AT&F                     OK
AT                          OK
AT-CMGF=1          ERROR

Can anyone explain why the third command gives an error?

I have tried AT+CSCS "GMS" which works, but AT-CMGF=1  stills gives an error.
Likewise AT+CMEE gives an error.
Best regards
torben

**Comment by eabase** [comment]
There is no AT "minus" SOMETHING. 
i think you can close this non issue

**Comment by SRGDamia1** [comment]
Are you still having problems with this?  I'm going to close this older issue.  Please re-open it if you're still having problems.

**Comment by Mich2899** [comment]
I am using Sim800C hat for raspberry pi. However, the image is not raspbian, it is buildroot and i am trying to send a text message using it. Commands and their response:
AT
OK
ATI
SIM800 R14.18
OK
AT+CMGF=1
ERROR
How can i solve this?
On raspbian with the same sim card i could send sms but on buildroot it gives error

**Comment by kemploe** [comment]
@Mich2899 

I occasionally have the exact same error on SIM900A as well
