### ISSUE TITLE
AT command  Tester 

### ISSUE THREAD

**Issue by HebaEbrahem** [vshymanskyy/TinyGSM#246]
Hellooo , Does anyone encountered that in the pic below before while using AT command tester software ?

My module is (GOOUUU IOT-GA6 ) , and i'm using usb-ttl converter to connect it
<img width="653" alt="problem" src="https://user-images.githubusercontent.com/20881623/53598174-b9417800-3bac-11e9-91ea-79efd690c1cf.png">

**Comment by vshymanskyy** [comment]
Please use the existing ticket which contains lots of info already: #164
