### ISSUE TITLE
[SIM800] WaitforNetwork doesn't actually wait for a network connection

### ISSUE THREAD

**Issue by SRGDamia1** [vshymanskyy/TinyGSM#25]
When I run waitForNetwork(), I expect that it will and keep trying until a connection is made.  But it seems to be making one attempt to get the network status and then just returning false.  In the code, I think the for loop of waitForNetwork() should actually be a while loop instead.  Am I doing something wrong?

```cpp
Serial.println(F("Waiting for network..."));  // For debugging
if (!_modem->waitForNetwork()){
  Serial.println("... Connection failed");  // For debugging
} else {
   _modem->gprsConnect(_APN, "", "");
}
```

**Comment by SRGDamia1** [comment]
I'm sorry.  I think it's actually an extra return statement.  PR issued.

**Comment by vshymanskyy** [comment]
Fixed. Thank you! See your PR for more comments.
