### ISSUE TITLE
write new function for SIM5320 3G Connect like "gprsConnect"

### ISSUE THREAD

**Issue by Najab** [vshymanskyy/TinyGSM#250]
I'm trying to working on SIM5320 for MQTT. I just want the 3G connected client which i'll use in pubsubClient Lib.
Please write new function for SIM5320 3G Connect like "gprsConnect".
Thanks in Advance.

**Comment by SRGDamia1** [comment]
Please stop opening redundant issues.  I don't know of anyone who has one of these chips that has the time or resources to integrate it into this library.
