### ISSUE TITLE
Data length SIM808 & PubSubClient

### ISSUE THREAD

**Issue by ChrSchultz** [vshymanskyy/TinyGSM#251]
Hello,
I send via mqtt.publish a json-string (length larger than 100 byte) and nothing  was send.  is there any possibility to trim datas in packets to send. (sorry for bad english) 
My Json-string: `{"_type":"location","tst":1052854452,"lon":48.71865,"lat":uCXhHvLeCWR18.99171,"alt":104.3,"vel":0.24} `
i want to add[code `"batt": 4,123` to the string, but then the string has a length of 115+ Byte and couldn't be sent.
thanks

**Comment by SRGDamia1** [comment]
PubSubClient (not Tiny GSM) has a default max packet size of 128. You can increase this in PubSubClient.h - it's MQTT_MAX_PACKET_SIZE.

**Comment by ChrSchultz** [comment]
yes, I know, but if i publish the full string - within `"batt";4.123"` over Mqtt via wifi it works the whole string will be sent. if i publish via GPRS(Tiny-GSM) nothing will be sent.

**Comment by SRGDamia1** [comment]
What are you using for "over MQTT via wifi?" You mean using the same PubSubClient library but a different arduino client library for wifi works but TinyGSM doesn't? Or do you mean you can send the request through another means and it is received? Did you try increasing the packet size in PubSubClient.h? Keep in mind that the packet size includes the MQTT header and topic, not just the data.

**Comment by ChrSchultz** [comment]
first I use PubSubClient with esp8266 and wifi and it works, with the large string (eg 115 Bytes), if I use   ESPClient(esp)TinyGSMClient sim808(esp) and PubSubClient mqtt(sim808) and publishing the large string (< 100 Bytes) with mqtt.publish(topic, payload).. nothing will be sent. 

I guess that either the communication between ESP and SIM808 limits the data, or the TinyGSM library...
there  TINY_GSM_RX_BUFFER 64 (bytes) defined....

**Comment by ChrSchultz** [comment]
fixed, i set TINY_GSM_RX_BUFFER to 128 and all works fine :-)

**Comment by SRGDamia1** [comment]
The rx buffer is for text coming from the SIM808 not going to it. I'm not sure I understand how it would fix your issue. But if increasing that fixes it for you, that's great!

**Comment by ChrSchultz** [comment]
RX means receicer and the rx- buffer Store datas coming From the Esp8622 which ist Computing the datas...
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 09.03.19, 21:13, Sara Damiano <notifications@github.com> schrieb:
The rx buffer is for text coming from the SIM808 not going to it. I'm not sure I understand how it would fix your issue. But if increasing that fixes it for you, that's great!

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vshymanskyy/TinyGSM","title":"vshymanskyy/TinyGSM","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/vshymanskyy/TinyGSM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SRGDamia1 in #251: The rx buffer is for text coming from the SIM808 not going to it. I'm not sure I understand how it would fix your issue. But if increasing that fixes it for you, that's great! "}],"action":{"name":"View Issue","url":"https://github.com/vshymanskyy/TinyGSM/issues/251#issuecomment-471217987"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/vshymanskyy/TinyGSM/issues/251#issuecomment-471217987",
"url": "https://github.com/vshymanskyy/TinyGSM/issues/251#issuecomment-471217987",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
