### ISSUE TITLE
SIM800 MQTT CONNECTION STUCK

### ISSUE THREAD

**Issue by shadababe04** [vshymanskyy/TinyGSM#267]
I USE SOFTWARE SERIAL TO COMMUNICATE WITH GSM MODEM PIN 2/3(RX/TX)

TinyGSM version: <0.3.5>
Hardware: <SIM800>

 I AM TRYING TO USE MQTT SERVICE OF THE LIBRARY 
Expected result   MQTT CONNECTION 

Actual result

Initializing modem....
Modem: SIM800 R13.08
12:52:56.715 -> Waiting for network... OK
12:53:01.940 -> Connecting to airtelgprs OK
=== MQTT NOT CONNECTED ===
12:53:08.538 -> Connecting to test.mosquitto.org OK
=== MQTT NOT CONNECTED ===
12:53:27.938 -> Connecting to test.mosquitto.org OK

**Comment by imranaalam** [comment]
show the code

**Comment by shadababe04** [comment]
now I rectify it... I think..it was a sim connection problem.thanks
