### ISSUE TITLE
[A6] connect to mqtt server is failed. and the state is -4.according to pubsubclient.it means the server didn't respond within the keepalive time

### ISSUE THREAD

**Issue by zhoufusong** [vshymanskyy/TinyGSM#27]
@xslim @vshymanskyy I use A6 + Nano and try to send data to mqtt server by GPRS. so I use the mqttclient example in this library.the mqtt server is OK because I have test it.but I get this result:  

Initializing modem...
Waiting for network... OK
Connecting to uninet OK

Connecting to MQTTServer fail
Connecting to MQTTServer fail
Connecting to MQTTServer fail
Connecting to MQTTServer fail
...

anyone can have any tips for me?

**Comment by henkbredell** [comment]
hi zhoufusong, have you been able to sort this problem out?  I am having same issues, but only on SIM800l with an Arduino.  Extending the MQTT_SOCKET_TIMEOUT 30 did not help.

**Comment by henkbredell** [comment]
I tried the higher baud rate of 115k baud and this solved the problem for me - as suggested by Holger in the other post.  For now this is working for me.  The GPRS unit I am using SIM800l has an auto bauding setting to make it very  easy to change the baudrate.

**Comment by vshymanskyy** [comment]
@zhoufusong did it help?

**Comment by psatya111** [comment]
I have the same issue with mqtt client with a6c gsm. any body resolved it?could you please share me the working code.my mail_id:psatya111@gmail.com.please help me.

**Comment by vshymanskyy** [comment]
![image](https://user-images.githubusercontent.com/1506708/30287445-c4dd7ddc-972d-11e7-8bb1-294ddfad64c5.png)
Just verified with A6 - everything works.

**Comment by amineazatour** [comment]
hi;
i had this problem and i resolve it by changing this command : mqtt.setServer(server, port);
by : PubSubClient (server, port, callback, client), to learn more this function you should visit this web site: https://pubsubclient.knolleary.net/api.html#PubSubClient2
and also and this is the most important , you have to disable the firewall of your PC if you use it as a mqtt broker. Good luck
