### ISSUE TITLE
if (!modem.isGprsConnected()) : error: invalid use of non-static member function

### ISSUE THREAD

**Issue by Mluis31** [vshymanskyy/TinyGSM#273]
Hi, i'm using a SIM800L and a ESP32 with Arduino IDE, I'm using this line:" if (!modem.isGprsConnected()) ESP.restart; " in order to restart the system when gsm connection is lost. But i'm getting this "error: invalid use of non-static member function" does anyone know why this happens?

**Comment by SRGDamia1** [comment]
Do you mean ```ESP.restart():```?

**Comment by Mluis31** [comment]
Yes.

**Comment by Mluis31** [comment]
Yes. But this way it works 
![image](https://user-images.githubusercontent.com/42934259/57239673-7674a400-7024-11e9-9a7a-6c50aaa5105a.png)

**Comment by SRGDamia1** [comment]
Yes, you need the open and close parenthesis after ```ESP.restart()```.  It shouldn't matter if it's on a new line with curly braces, as long as that would be the only statement inside the curly braces.
