### ISSUE TITLE
how to make check on payload to perform action in subscribe topic

### ISSUE THREAD

**Issue by shadababe04** [vshymanskyy/TinyGSM#275]
TinyGSM version: 
Hardware:

**Comment by SRGDamia1** [comment]
I don't understand your issue.

**Comment by shadababe04** [comment]
in the given example, led status change on/off if the matching topic is received but I want to change the led status on payload attached with the topic.like
when i get ON in payload then led on and off with off.

**Comment by SRGDamia1** [comment]
Now I understand what you're trying to do, but the support for that is way outside the scope of this library.

This library only provides the client architecture.  MQTT support would come from another library that rides on top of that architecture.  Topic parsing and LED control would be yet another layer above the MQTT support.
