### ISSUE TITLE
Hello Everyone, I got a question. Is the TinyGSM Library compatible with the new Simcom 7020 Module.

### ISSUE THREAD

**Issue by Darvesh7** [vshymanskyy/TinyGSM#277]
TinyGSM version: 
Hardware:

**Comment by SRGDamia1** [comment]
No.  It looks like the 7020 uses different commands than the 7000.  Feel free to make a pull request.

**Comment by eabase** [comment]
>  It looks like the 7020 uses different commands than the 7000.

That's why nobody should use SIMcom! Every single module is doing something different or using different AT commands for doing the same.
