### ISSUE TITLE
Ordering of calls responseStatusCode and responseBody

### ISSUE THREAD

**Issue by tkralj** [vshymanskyy/TinyGSM#294]
Hello, I'm not sure if it is a bug but i will report it anyway. It looks like it is not all the same if i call responseBody first and then responseStatusCode  or other way around. If I call responseBody first i get response body. If i call responseStatusCode   afer responseBody  it always returns -3.

If i first call responseStatusCode   then I get correct status . The responseBody  works as expected no matter when i call it.

**Comment by SRGDamia1** [comment]
Are you sure this is an issue with TinyGSM and not the HttpClient library?

**Comment by tkralj** [comment]
Not sure, it could be both ways either TinyGsmClient or HttpClient. I posted issues on boht githubs.

**Comment by SRGDamia1** [comment]
I'm going to close this issue.  Please re-open it if you're still having issues.
