### ISSUE TITLE
Any chance you would be able to add AT+CIPGSMLOC ?

### ISSUE THREAD

**Issue by evmond** [vshymanskyy/TinyGSM#3]
Hi There, 

Big fan of your work here. Was wondering if there is any chance of adding AT+CIPGSMLOC for location triangulation. Would be great for IoT dashboards which have map widgets

**Comment by VittorioEsposito** [comment]
@evmond Working on it in my library

**Comment by VittorioEsposito** [comment]
@evmond Just added [here](https://github.com/VittorioEsposito/Sim800L-Arduino-Library-revised/releases)

**Comment by vshymanskyy** [comment]
Sure, will be added. This stuff is much simple than providing proper GPRS support ;)

**Comment by ethernutza** [comment]
Hello

For a noob like me this is a winner! Thank you very much! Any chance you can add getIMEI to this library or is that pushing it?

**Comment by vshymanskyy** [comment]
Added some functions:
```
  modem.setGsmBusy();
  String imei = modem.getIMEI();
  int signal = modem.getSignalQuality();
  String loc = modem.getGsmLocation();
```

**Comment by ethernutza** [comment]
Brilliant! Thank you very much!

**Comment by sanjulanipun** [comment]
hi @vshymanskyy  any possible to add `AT+CNUM` for sim7600 to get sim card number ?

or any way have to send that custom at command with this library and get a response and filter it?

**Comment by vshymanskyy** [comment]
Yes, both are possible ;) will look into it
