### ISSUE TITLE
esp32 compile error: "cannot declare variable 'http' to be of abstract type 'HttpClient' "

### ISSUE THREAD

**Issue by danirebollo** [vshymanskyy/TinyGSM#306]
TinyGSM version: 0.7.9
Hardware: ESP32 Wrover Module

### Scenario, steps to reproduce
Can't compile HttpsClient example

> HttpsClient:94:12: error: cannot declare variable 'http' to be of abstract type 'HttpClient'
> 
>  HttpClient http(client, server, port);

**Comment by SRGDamia1** [comment]
The Arduino HttpClient library is not compatible with the most current version of the ESP32's core.  *This* library is, but you can't use the HttpClient.  Please comment on the issue in the ESP32 core:  https://github.com/espressif/arduino-esp32/issues/2755.
