### ISSUE TITLE
TLS autonegotiation

### ISSUE THREAD

**Issue by danirebollo** [vshymanskyy/TinyGSM#307]
TinyGSM version: 0.7.9
Hardware: ESP32 Wrover Module

I tried HTTPS and MQTT (with TLS) to Azure over Wifi and works well (without the need of load/store any certificate manually), but when I try with SIM868 and TinyGSM the firmware restarts at compile time or not getting nothing from server. 

Checking libraries, TinyGSM do AT+CIPSSL=1 using built in certificates, but I have no Azure certificate loaded (Azure uses DigiCert Baltimore Root Certificate ).

It is possible to force to use software TLS with mbedTLS  like built in Wifi Libraries or other software approach instead SIM868 Hardware TLS capabilities to achieve autonegotiation?

**Comment by vshymanskyy** [comment]
For ESP32, it is bar better to use PPPoS library from ESP-IDF, which uses the IP/TLS stack of ESP32 for GSM communication. But unfortunately I could not find any example off using PPPoS on Arduino.
You can follow this ticket: https://github.com/espressif/arduino-esp32/issues/1858
