### ISSUE TITLE
Library that just fail

### ISSUE THREAD

**Issue by XuTpuK** [vshymanskyy/TinyGSM#31]
Hi!
I have Mega2560, SIM800L and standard wiring:
SIM800L has separate strong power.
Mega TX -> SIM RX0
Mega RX -> SIM TX0

After sketch started, I open Serial Monitor and see rubbish (mostly empty squares). Maybe speed? At bottom of Monitor speed is 9600, obviously not a problem. Library which just fails...
I didn't run 'Diagnostics', because it requires downloading other lib, what is boring. Just stopped.

**Comment by narzul** [comment]
That depends on what you have set the baud rate to be, the default when you open an example are SerialAT.begin(115200). I have used it with Mega2560 and Mega1280, with out any problems.
If you have pin number on the simcard you need to add it to the script or put the sim into a mobil and disable pin number.

**Comment by vshymanskyy** [comment]
"Library which just fails... I didn't run 'Diagnostics', because it requires downloading other lib, what is boring. Just stopped."
I'm not blaming you... ;) Just find a better lib.
