### ISSUE TITLE
More examples needed

### ISSUE THREAD

**Issue by sandhan26** [vshymanskyy/TinyGSM#32]
Featues like sending & receiving sms, etc.

**Comment by noctilucentsky** [comment]
Hello,

Did you figure out how to use the sendSMS methods on the SIM800L?

I have been knocking my head down on that one, it just doesnt send anything.

An example would be apreciated.

**Comment by noctilucentsky** [comment]
`1
2
3
AT

OK
AT&FZE0

OK
AT+CPIN?

+CPIN: READY

OK
5
AT+CMGF=1

OK
AT+CMGS="0769879696"

>Text here lol `

**Comment by sandhan26** [comment]
yes, I have been able to send as well as receive SMS using TinyGSM library, but i used SIM900A.
