### ISSUE TITLE
How to detect if SIM card is present?

### ISSUE THREAD

**Issue by GeirFrimann** [vshymanskyy/TinyGSM#333]
Not an issue, but I would like to know the easiest way to detect if a SIM card are present or not.
I'm using a MCU that has both a SIM800L and WiFi. If there is no SIM card present I would to connect to  WiFi instead, without waiting for timeouts from trying to connect to GPRS.

**Comment by GeirFrimann** [comment]
Not an issue, but I would like to know the easiest way to detect if a SIM card is present or not

**Comment by SRGDamia1** [comment]
Try the ```getSimStatus()``` or ```getSimCCID()``` functions.
