### ISSUE TITLE
fixed getSimCCID() unhandled 

### ISSUE THREAD

**Issue by VinceKezel** [vshymanskyy/TinyGSM#336]
Using TisyGSM 0.7.9 on module SIM868 ... running examples/AllFunctions.ino

the part of sketch that does modem.getSimCCID() and modem.getIMEI()shows this in serial monitor:
```AT+CCID

8944501810180244540f

OK
[33283] ### Unhandled: 8944501810180244540f

OK
[33288] CCID: 
AT+GSN

868183038764457

OK
```
This sim number comes out unhandled.
I found out that if I changed line 481 of TinyGsmCommon.h to remove  **_"+CCID"_** then the sim number gets returned normally to modem.getSimCCID(). Basically I just made the getSimCCID match what was already working for getIMEI.

**Comment by kduma** [comment]
I'm confirming that this problem exists also on SIM808 modem.
