### ISSUE TITLE
Possible bug in connected() function in tinygsm800

### ISSUE THREAD

**Issue by arihantdaga** [vshymanskyy/TinyGSM#342]
## What type of issues is this?

[x] Bug or issue with library functionality (ie, sending data over TCP/IP)

### What are you working with?
Sim800 Module, using latest tinygsm library. 

Code: 

### Scenario, steps to reproduce
I use pubsub client with sim800 and this library. If i set wrong username and password for the mqtt client. It gets into a strange loop where it keeps printing AT+CIPCLOSE=1 continuously and mqtt.connected() is returning true.
While it should be returning false. Because actually the connection has been closed. 
 
### AT command log
It happens during a point, when available() function returns 4, because sock_available is 4, but sock_connected is false. And if available() returns any non zero value. connected() assumes that it is connected and returns true always. 

And Pubsubclient would keep assuming that the _client is connected, and available length is 4 so it keeps sending client->stop. 

I think we should also check for sock_connected in connected() always. or set sock_available to 0 somewhere. 
Or Shall we also reset sock_available to 0 in the stop() function.

**Comment by SRGDamia1** [comment]
This should be fixed.
