### ISSUE TITLE
MQTT unable to subscribe 

### ISSUE THREAD

**Issue by surajjorwekar** [vshymanskyy/TinyGSM#345]
[ Possible Bug] Unable to subscribe to the topic

Main processor board: ESP32
Modem:  Doit Wroom
TinyGSM version: (0.9.17) 
Code: MqttClient.ino

Am trying to publish and subscribe but unfortunately am only able to publish data and not subscribe to it.
Any possible issue in library? using latest PubSub and TinyGSM

**Comment by SRGDamia1** [comment]
You should be able to subscribe as well.

**Comment by SRGDamia1** [comment]
I'm going to close this issue.  Please re-open it if you're still having issues.
