### ISSUE TITLE
Arduino Mega - SIM800L - MqttClient.ino -- unable to connect to the mqtt broker

### ISSUE THREAD

**Issue by thecrow159** [vshymanskyy/TinyGSM#358]
## What type of issues is this?

[ x ] Bug or issue with library functionality (ie, sending data over TCP/IP)
       --> Modem is **not able to connect to the Mqtt Broker**

### What are you working with?

Main processor board: **Arduino Mega**
Modem: **SIM800L R14.18**
TinyGSM version: **0.7.9**
Code: **MqttClient.ino**

### Scenario, steps to reproduce
The modem can't connect to the mqtt broker, giving message **=== MQTT NOT CONNECTED ===**

### Expected result
Connection done with the broker

### Actual result
The Diagnostics.ino sketch exit with PASSED result.
Modem in factory default.
https://gist.github.com/thecrow159/51ec214276e2629838ebd277ef0c9ce3

### AT command log
Read above

**Comment by SRGDamia1** [comment]
Connecting to MQTT on the SIM800 works fine - but the test.mosquitto.org broker often doesn't. It's a broker problem, not a TinyGSM one.  Try a different test broker or the broker you actually will use.  I usually have much better luck with broker.hivemq.com than test.mosquitto.org.

**Comment by thecrow159** [comment]
Hi SRGDamia1, here is the log with broker.hivemq.com. Thank you for replying

`13:28:44.201 -> Initializing modem...
13:28:44.201 -> AT
13:28:44.201 -> 
13:28:44.201 -> Call Ready
13:28:44.201 -> 
13:28:44.201 -> SMS Ready
13:28:44.201 -> 
13:28:44.201 -> OK
13:28:44.201 -> AT+CLTS=1
13:28:44.234 -> 
13:28:44.234 -> OK
13:28:44.234 -> AT&W
13:28:44.234 -> 
13:28:44.234 -> OK
13:28:44.234 -> AT+CFUN=0
13:28:44.599 -> 
13:28:44.599 -> +CPIN: NOT READY
13:28:49.280 -> 
13:28:49.280 -> OK
13:28:49.280 -> AT+CFUN=1,1
13:28:49.280 -> 
13:28:49.280 -> OK
13:28:52.301 -> [11080] ### TinyGSM Version: 0.7.9
13:28:52.301 -> AT
13:28:52.301 -> ⸮⸮[11283] ### Unhandled: ⸮⸮
13:28:52.566 -> AT
13:28:52.600 -> 
13:28:52.600 -> OK
13:28:52.600 -> AT&FZ
13:28:52.600 -> 
13:28:52.600 -> OK
13:28:52.600 -> ATE0
13:28:52.600 -> ATE0

13:28:52.600 -> OK
13:28:52.600 -> AT+GMM
13:28:52.600 -> 
13:28:52.600 -> SIMCOM_SIM800L
13:28:52.600 -> 
13:28:52.600 -> OK
13:28:52.600 -> [11412] ### Modem: SIMCOM SIM800L
13:28:52.600 -> [11412] ### Modem: SIMCOM SIM800L
13:28:52.633 -> AT+CPIN?
13:28:52.633 -> 
13:28:52.633 -> ERROR
13:28:53.630 -> AT+CPIN?
13:28:53.630 -> 
13:28:53.630 -> RDY
13:28:53.630 -> 
13:28:53.630 -> +CFUN: 1
13:28:53.630 -> 
13:28:53.630 -> ERROR
13:28:54.625 -> AT+CPIN?
13:28:54.625 -> 
13:28:54.625 -> ERROR
13:28:55.632 -> AT+CPIN?
13:28:55.632 -> 
13:28:55.632 -> +CPIN: READY
13:28:55.665 -> 
13:28:55.665 -> +CPIN: READY
13:28:55.665 -> 
13:28:55.665 -> OK
13:28:55.665 -> ATI
13:28:55.665 -> 
13:28:55.665 -> SIM800 R14.18
13:28:55.665 -> 
13:28:55.665 -> OK
13:28:55.665 -> Modem: SIM800 R14.18
13:28:55.665 -> Waiting for network...AT+CREG?
13:28:55.665 -> 
13:28:55.665 -> +CREG: 0,2
13:28:55.665 -> 
13:28:55.665 -> OK
13:28:55.931 -> AT+CREG?
13:28:55.931 -> 
13:28:55.931 -> +CREG: 0,2
13:28:55.931 -> 
13:28:55.931 -> OK
13:28:56.196 -> AT+CREG?
13:28:56.196 -> 
13:28:56.196 -> +CREG: 0,2
13:28:56.196 -> 
13:28:56.196 -> OK
13:28:56.429 -> AT+CREG?
13:28:56.462 -> 
13:28:56.462 -> +CREG: 0,2
13:28:56.462 -> 
13:28:56.462 -> OK
13:28:56.695 -> AT+CREG?
13:28:56.728 -> 
13:28:56.728 -> +CREG: 0,2
13:28:56.728 -> 
13:28:56.728 -> OK
13:28:56.960 -> AT+CREG?
13:28:56.960 -> 
13:28:56.960 -> +CREG: 0,2
13:28:56.960 -> 
13:28:56.960 -> OK
13:28:57.226 -> AT+CREG?
13:28:57.226 -> 
13:28:57.226 -> +CREG: 0,2
13:28:57.226 -> 
13:28:57.226 -> OK
13:28:57.491 -> AT+CREG?
13:28:57.491 -> 
13:28:57.491 -> +CREG: 0,2
13:28:57.491 -> 
13:28:57.491 -> OK
13:28:57.757 -> AT+CREG?
13:28:57.757 -> 
13:28:57.757 -> +CREG: 0,2
13:28:57.757 -> 
13:28:57.757 -> OK
13:28:57.989 -> AT+CREG?
13:28:58.022 -> 
13:28:58.022 -> +CREG: 0,2
13:28:58.022 -> 
13:28:58.022 -> OK
13:28:58.255 -> AT+CREG?
13:28:58.255 -> 
13:28:58.255 -> Call Ready
13:28:58.255 -> 
13:28:58.255 -> +CREG: 0,2
13:28:58.288 -> 
13:28:58.288 -> OK
13:28:58.521 -> AT+CREG?
13:28:58.521 -> 
13:28:58.521 -> +CREG: 0,2
13:28:58.521 -> 
13:28:58.521 -> OK
13:28:58.786 -> AT+CREG?
13:28:58.786 -> 
13:28:58.786 -> SMS Ready
13:28:58.786 -> 
13:28:58.786 -> +CREG: 0,1
13:28:58.786 -> 
13:28:58.786 -> OK
13:28:58.786 ->  OK
13:28:58.786 -> AT+CREG?
13:28:58.819 -> 
13:28:58.819 -> +CREG: 0,1
13:28:58.819 -> 
13:28:58.819 -> OK
13:28:58.819 -> Network connected
13:28:58.819 -> AT+CIPRXGET=4,1
13:28:58.819 -> 
13:28:58.819 -> ERROR
13:28:58.819 -> [17616] ### Available: 0 on 1
13:28:58.819 -> AT+CIPSTATUS=1
13:28:58.819 -> 
13:28:58.819 -> ERROR
13:29:00.839 -> === MQTT NOT CONNECTED ===
13:29:00.839 -> Connecting to broker.hivemq.comAT+CIPRXGET=4,1
13:29:00.839 -> 
13:29:00.839 -> ERROR
13:29:00.839 -> [19637] ### Available: 0 on 1
13:29:00.839 -> AT+CIPSTATUS=1
13:29:00.839 -> 
13:29:00.839 -> ERROR
13:29:02.863 -> AT+CIPCLOSE=1,1
13:29:02.863 -> 
13:29:02.863 -> ERROR
13:29:02.863 -> AT+CIPSSL=0
13:29:02.863 -> 
13:29:02.863 -> OK
13:29:02.863 -> AT+CIPSTART=1,"TCP","broker.hivemq.com",1883
13:29:02.863 -> 
13:29:02.863 -> ERROR
13:29:02.863 ->  fail
13:29:02.996 -> AT+CIPRXGET=4,1
13:29:02.996 -> 
13:29:02.996 -> ERROR
13:29:02.996 -> [21783] ### Available: 0 on 1
13:29:02.996 -> AT+CIPSTATUS=1
13:29:02.996 -> 
13:29:02.996 -> ERROR
13:29:04.987 -> === MQTT NOT CONNECTED ===
13:29:05.087 -> AT+CIPRXGET=4,1
13:29:05.120 -> 
13:29:05.120 -> ERROR
13:29:05.120 -> [23901] ### Available: 0 on 1
13:29:05.120 -> AT+CIPSTATUS=1
13:29:05.120 -> 
13:29:05.120 -> ERROR
13:29:07.111 -> === MQTT NOT CONNECTED ===
13:29:07.211 -> AT+CIPRXGET=4,1
13:29:07.211 -> 
13:29:07.211 -> ERROR
13:29:07.211 -> [26018] ### Available: 0 on 1
13:29:07.244 -> AT+CIPSTATUS=1
13:29:07.244 -> 
13:29:07.244 -> ERROR
13:29:09.235 -> === MQTT NOT CONNECTED ===
13:29:09.335 -> AT+CIPRXGET=4,1
13:29:09.335 -> 
13:29:09.335 -> ERROR
13:29:09.335 -> [28136] ### Available: 0 on 1
13:29:09.335 -> AT+CIPSTATUS=1
13:29:09.335 -> 
13:29:09.335 -> ERROR
13:29:11.359 -> === MQTT NOT CONNECTED ===
13:29:11.359 -> Connecting to broker.hivemq.comAT+CIPRXGET=4,1
13:29:11.359 -> 
13:29:11.359 -> ERROR
13:29:11.359 -> [30153] ### Available: 0 on 1
13:29:11.359 -> AT+CIPSTATUS=1
13:29:11.359 -> 
13:29:11.359 -> ERROR
13:29:13.383 -> AT+CIPCLOSE=1,1
13:29:13.383 -> 
13:29:13.383 -> ERROR
13:29:13.383 -> AT+CIPSSL=0
13:29:13.383 -> 
13:29:13.383 -> OK
13:29:13.383 -> AT+CIPSTART=1,"TCP","broker.hivemq.com",1883
13:29:13.383 -> 
13:29:13.416 -> ERROR
13:29:13.416 ->  fail
13:29:13.516 -> AT+CIPRXGET=4,1
13:29:13.516 -> 
13:29:13.516 -> ERROR
13:29:13.516 -> [32300] ### Available: 0 on 1
13:29:13.516 -> AT+CIPSTATUS=1
13:29:13.516 -> 
13:29:13.516 -> ERROR
13:29:15.507 -> === MQTT NOT CONNECTED ===
13:29:15.639 -> AT+CIPRXGET=4,1
13:29:15.639 -> 
13:29:15.639 -> ERROR
13:29:15.639 -> [34419] ### Available: 0 on 1
13:29:15.639 -> AT+CIPSTATUS=1
13:29:15.639 -> 
13:29:15.639 -> ERROR
13:29:17.632 -> === MQTT NOT CONNECTED ===
13:29:17.731 -> AT+CIPRXGET=4,1
13:29:17.764 -> 
13:29:17.764 -> ERROR
13:29:17.764 -> [36537] ### Available: 0 on 1
13:29:17.764 -> AT+CIPSTATUS=1
13:29:17.764 -> 
13:29:17.764 -> ERROR
13:29:19.756 -> === MQTT NOT CONNECTED ===
13:29:19.855 -> AT+CIPRXGET=4,1
13:29:19.855 -> 
13:29:19.855 -> ERROR
13:29:19.855 -> [38657] ### Available: 0 on 1
13:29:19.855 -> AT+CIPSTATUS=1
13:29:19.889 -> 
13:29:19.889 -> ERROR
13:29:21.879 -> === MQTT NOT CONNECTED ===
13:29:21.879 -> Connecting to broker.hivemq.comAT+CIPRXGET=4,1
13:29:21.879 -> 
`

**Comment by thecrow159** [comment]
I sorted it out. I had same issue of #318.
I installed the library directly from the IDE a week ago.

**Comment by thecrow159** [comment]
In the MqttClient.ino example sketch (the last this time ..) I can see in the top description:

>  * Subscribe for messages:
>  *   mosquitto_sub -h test.mosquitto.org -t GsmClientTest/init -t GsmClientTest/ledStatus -q 1
>  * Toggle led:
>  *   mosquitto_pub -h test.mosquitto.org -t GsmClientTest/led -q 1 -m "toggle"

while in the sketch the broker is "broker.hivemq.com".

So there's a broker host mismatch

**Comment by ortegafernando** [comment]
top description are comments. Don't worry.
I have the same error as you. May be anyone could help us.

**Comment by thecrow159** [comment]
Yes, I'm using a mosquitto local server with auth login and everything is working now. Thank you
