### ISSUE TITLE
MC60 is not working with this library, Can you please fix this issue? 

### ISSUE THREAD

**Issue by shridattdudhat** [vshymanskyy/TinyGSM#370]
## What type of issues is this?

[ ] Request to support a new module
    
[ ] Bug or problem compiling the library
[ ] Bug or issue with library functionality (ie, sending data over TCP/IP)

### What are you working with?

Main processor board: 
Modem: 
TinyGSM version: 
Code:

**Comment by SRGDamia1** [comment]
Duplicate
