### ISSUE TITLE
error: 'Stream& TinyGsmSim800::stream' is protected within this context

### ISSUE THREAD

**Issue by brvdg** [vshymanskyy/TinyGSM#373]
Hi,

I upgraded my project to the latest TinyGSM Lib.
Unfortunately the stream function is now protected and not public.

It's possible to get the stream back into the public scope?

If I set the line 723 in the TinyGsmClientSIM800.h to public everything works fine.

Also the SIM800_SslSetCert example doesn't work with the actual version.

Thanks!

**Comment by SRGDamia1** [comment]
I've made it public again in 0.10.2.  Sorry about that.
