### ISSUE TITLE
How to use HTTPS rest api in sim800l?

### ISSUE THREAD

**Issue by biswajitjei02** [vshymanskyy/TinyGSM#410]
here is the example of HTTPS  GET /POST  as this data base  shows please check
https://firebase.google.com/docs/reference/rest/database.

how to ue https request using Tiny GSM library for data base .

**Comment by SRGDamia1** [comment]
Based on #407 it seems someone else was able to help you out.

In general, though, this isn't the place to ask someone to write out code for you.

**Comment by star297** [comment]
![image](https://user-images.githubusercontent.com/6283197/108568145-d62b6480-7309-11eb-8d55-fd5cd1033845.png)


How to implement the RESTful API as shown on your web RREADME.md?
Are there any examples for using GET, POST, PUT and DELETE as used with Firebase?
Can this TinyGSM library actually handle the REST API functions?
