### ISSUE TITLE
SIM800 modem.gprsConnect(apn, gprsUser, gprsPass) Blocking

### ISSUE THREAD

**Issue by MadZoids** [vshymanskyy/TinyGSM#411]
is the modem.gprsConnect(apn, gprsUser, gprsPass) function a blocking function?
cause when i call it seems blocking

### Blocking the timestamp Print on Connect
```
44:20
44:21
44:22
44:23
44:24
Wait...
Connecting to internet success
GPRS connected
44:31
44:32
44:33
44:34
```

**Comment by SRGDamia1** [comment]
Yes.
