### ISSUE TITLE
TinyGSMClientSecure does not name a type

### ISSUE THREAD

**Issue by far1998** [vshymanskyy/TinyGSM#423]
[v] I have read the Troubleshooting section of the ReadMe

## What type of issues is this?

[ ] Request to support a new module
    
[ ] Bug or problem compiling the library
[v] Bug or issue with library functionality (ie, sending data over TCP/IP)
[v] Question or request for help

### What are you working with?

Modem: DFRobot SIM7000E
Main processor board: Arduino UNO
TinyGSM version: 0.10.6
Code: `TinyGsmClientSecure client(modem);`
`----------------`
`if (!modem.hasSSL()) {
    SerialMon.println(F("SSL is not supported by this modem"));
    while(true) { delay(1000); }
  }`

### Expected result
The board should upload the file with SSL support

### Actual result
`GPSTrackerFirebase:38:1: error: 'TinyGsmClientSecure' does not name a type; did you mean 'TinyGsmClient'?
 TinyGsmClientSecure client(modem);
 ^~~~~~~~~~~~~~~~~~~
 TinyGsmClient
GPSTrackerFirebase:39:18: error: 'client' was not declared in this scope
 HttpClient https(client, server, port);
                  ^~~~~~
C:\Users\farha\OneDrive\Documents\GPSTrackerFirebase\GPSTrackerFirebase.ino:39:18: note: suggested alternative: 'Client'
 HttpClient https(client, server, port);
                  ^~~~~~
                  Client
C:\Users\farha\OneDrive\Documents\GPSTrackerFirebase\GPSTrackerFirebase.ino: In function 'void initializeModem()':
GPSTrackerFirebase:168:14: error: 'TinyGsm {aka class TinyGsmSim7000}' has no member named 'hasSSL'
   if (!modem.hasSSL()) {
              ^~~~~~
exit status 1
'TinyGsmClientSecure' does not name a type; did you mean 'TinyGsmClient'?`

### Debug and AT command log
----

TinyGSMClientSecure does not name a type, are you sure it is still there or it is already removed?
I try to see the code but it seems like it doesn't support secure mode (SSL)

**Comment by SRGDamia1** [comment]
SSL isn't supported yet on the SIM7000 series.

**Comment by EmanueleFeola** [comment]
@far1998a ssl support for sim7000 is in phase of development, I tested it and it is working. Here there is the discussion #437
