### ISSUE TITLE
Is this library for chips using 3G or NB-IoT?

### ISSUE THREAD

**Issue by ZebNZ** [vshymanskyy/TinyGSM#441]
Hi all,

I am new to this GSM subject. I am wondering if this library is for chips using 3G or NB-IoT?

Thanks,

Zeb

**Comment by SRGDamia1** [comment]
yes.

**Comment by ZebNZ** [comment]
@SRGDamia1 what does "yes" mean? Are you saying that this library is for NB-IoT and for 3G?

Thanks,

Zeb

**Comment by ZebNZ** [comment]
And the code is the same, you just configure the SIM card to what you want (3G or NB-IoT)?

**Comment by SRGDamia1** [comment]
Yes, to all of those.
