### ISSUE TITLE
How do you handle incoming calls?

### ISSUE THREAD

**Issue by bokolob** [vshymanskyy/TinyGSM#464]
Hello.

I found it neither in code nor examples nor docs...

[ ] I have read the Troubleshooting section of the ReadMe

## What type of issues is this?

[ ] Request to support a new module
    
[ ] Bug or problem compiling the library
[ ] Bug or issue with library functionality (ie, sending data over TCP/IP)
[ ] Question or request for help

### What are you working with?

Modem: 
Main processor board: 
TinyGSM version: 
Code:

**Comment by SRGDamia1** [comment]
We don't.

**Comment by bokolob** [comment]
But is there a way to do it with your library?

**Comment by SRGDamia1** [comment]
There's a ```callAnswer()``` and a ```callHangup()``` function implemented for some of the modules, but there is not any support at this time for listening for an incoming call so you would have to have some other way of knowing there's an call coming (ie, a pin interrupt) and handle everything inside the call outside of this library.
