### ISSUE TITLE
Has no member named 'networkConnect'

### ISSUE THREAD

**Issue by Cutiino** [vshymanskyy/TinyGSM#472]
Hello, I am trying connect TTGo Tcall ESP32 to Wifi throught of modem.networkConnect(wifiSSID, wifiPass) function, however, it always have a issue and don't compile it. The issue shows that I have is: "'TinyGsm {aka class TinyGsmSim800}' has no member named 'networkConnect'"
I followed all the steps of the library but I couldn't fix the issue.
To the connection with GPRS I don't have problem but also, I would like connect me to Wifi and be able to use both connections.

**Comment by SRGDamia1** [comment]
The SIM800 is a cellular chip, not WiFi.  You can't use WiFi commands with it.  The ESP module in this library is for communicating with an ESP programmed with AT firmware, not for using the ESP itself as the main brain.  If you're using the ESP32 as your mcu (as you probably are) and the attached SIM800 as your cellular component, you need to use the WiFi commands for whatever core you're using on your ESP and then TinyGSM only for communication with the SIM800.
