### ISSUE TITLE
When will be support SSL/TLS (HTTPS) for SIM7000?

### ISSUE THREAD

**Issue by EchoSystemMark** [vshymanskyy/TinyGSM#474]
In the TinyGSM library, SSL/TLS support for SIM 7000 is listed as TODO. 
( //typedef TinyGsmSim7000::GsmClientSecureSim7000 TinyGsmClientSecure; TODO! ). 
Everyone has been waiting for this for a long time, when is it planned to be implemented?

**Comment by SRGDamia1** [comment]
I'm sorry, it's not a feature that any projects I'm on need, so I don't have any plans to do it. There have been several other issues where people have mentioned working on it. If someone submits a solid pull request, I will accept it.

**Comment by FStefanni** [comment]
Hi,

seems duplicate of #437 (I know since I am also interested in this feature :-) ).
@EchoSystemMark I suggest to try some of the forks there proposed (this is what I am going to do).
I believe this issue could be closed as duplicate.

Regards.
