### ISSUE TITLE
Http Post

### ISSUE THREAD

**Issue by facetime88** [vshymanskyy/TinyGSM#48]
Hi,

I am trying to send some args to a web server. The example is showing fine with HTTP get below:

 

> client.print(String("GET ") + resource + " HTTP/1.0\r\n");
client.print(String("Host: ") + server + "\r\n");
client.print("Connection: close\r\n\r\n");`

But how do I achieve for POST method?
Thanks.

**Comment by vshymanskyy** [comment]
Sorry this is not related to GSM. Hust google about HTTP rrquests.

**Comment by Tucsondirect** [comment]
i have this problem as well the library seems to be not cooperative when attempting POST requests
