### ISSUE TITLE
Typo in example Diagnostics

### ISSUE THREAD

**Issue by woodlist** [vshymanskyy/TinyGSM#517]
[x] I have read the Troubleshooting section of the ReadMe

## What type of issues is this?

[ ] Request to support a new module
    
[ ] Bug or problem compiling the library
[x] Bug or issue with library functionality (ie, sending data over TCP/IP)
[ ] Question or request for help

### What are you working with?

Modem: 
Main processor board: 
TinyGSM version: 
Code: 

### Debug and AT command log

Line 161: GSM_PIN is not boolean type and could not be compared with integer 3. It is senseless.

**Comment by SRGDamia1** [comment]
It's not being compared to 3, line 161 just checks if GSM_PIN has been defined as anything valid.  The sim status is compared to 3.
