### ISSUE TITLE
Sending Http header through Sim808

### ISSUE THREAD

**Issue by Latanshu** [vshymanskyy/TinyGSM#52]
Hi,

Can you please guide me how to send HTTP Header. Using Sim808 with Arduino Uno. Trying to connecting to Dweetpro.io. Need to pass X-DWEET-AUTH value in the header.

Successfully connected to Dweet.io, as that doesn't require to pass any data in the header.

Below is the code I tried unsuccessfully. 

  if (client.connect(https://dweetpro.io, 443)) {
    Serial.println(" fail");
    delay(10000);
    return;
  }  
  client.println("POST /v2/dweets HTTP/1.1");
    Serial.println(1);// For debugging  
  client.println("Host: dweetpro.io");
  Serial.println(2);// For debugging  
  client.println("X-DWEET-AUTH: XYZ");
  Serial.println(3);// For debugging  
  client.println("Accept: application/json");
  Serial.println(4);// For debugging  
  client.println("Content-Type: application/json");
  Serial.println(5);// For debugging  
  client.print("Content-Length: ");
  Serial.println(6); // For debugging
  client.println(144);
  client.println();
  Serial.println(7); // For debugging  
  client.print(PostData);
  Serial.println(PostData);

**Comment by vshymanskyy** [comment]
You're trying to.make https request. please use plain http if possible.
