### ISSUE TITLE
Core 0 on ESP32 + SIM800L

### ISSUE THREAD

**Issue by yaroshd81** [vshymanskyy/TinyGSM#542]
if use core 0 on ESP32 we have problem: 
> Task watchdog got triggered. The following tasks did not reset the watchdog in time:
I fix this problem this way:
```
#ifndef TINY_GSM_YIELD_MS
#define TINY_GSM_YIELD_MS 1//in original file (TinyGsmCommon.h) we have 0
#endif
```

**Comment by SRGDamia1** [comment]
You can just add the define to your program rather than changing the library.

**Comment by yaroshd81** [comment]
I understand, I share my experience with the community

**Comment by SRGDamia1** [comment]
I don't know that anyone else has ever had an issue with the program crashing without the define.  Are you sure it's not something else?  Usually you only need that define for a fast processor and slow baud rate and the symptoms are unstable AT communication not crashes.

**Comment by yaroshd81** [comment]
On core 1 all working w/o changes. But core 0 call watchdog and reboot device. When i change to `#define TINY_GSM_YIELD_MS 1` - i don't have "cernel panic" :)
