### ISSUE TITLE
[other] SSL Client compatible with TinyGSM and ESP32 boards

### ISSUE THREAD

**Issue by Kromtar** [vshymanskyy/TinyGSM#549]
Hello everybody :)

I want to tell you that I have been testing [this library](https://github.com/govorox/SSLClient) which has turned out to be very useful to establish SSL connection using ESP32 based boards. I know there are many questions and problems with establishing secure connections using TinyGSM.
The solution will always depend on your particular board, the model of the modem, the type of connection and several other factors.

In my case this library [easily solved](https://github.com/govorox/SSLClient) my problems. I have successfully tested it on ESP32 with SIM800L and SIM7000G.

I hope that for someone it may be useful.
Thank you maintainers and collaborators of TinyGSM.

**Comment by nickagian** [comment]
Hi @Kromtar,

would you mind posting an example working code that combines the two libraries?
Because in my code I'm not able to run it successfully. I get a core panic error and it is rather difficult to debug.

**Comment by Kromtar** [comment]
In the [examples folder](https://github.com/govorox/SSLClient/tree/master/examples/Esp32) you can find fully functional codes.

**Comment by vshymanskyy** [comment]
Thank you. I think this may be worth mentioning in the README

**Comment by rtrombetta** [comment]
Hi @Kromtar!

I'm working on a project using the LiliGO T-SIM7000G board. Using the native functions of TinyGSM to conectar using SSL (TINY_GSM_MODEM_SIM7000SSL), despite not having any error during compilation, in my case the connections do not work. I tryed some exemples with https and mqtt. With the library you posted, everything worked perfectly defining the modem as TINY_GSM_MODEM_SIM7000. Both HTTPS and MQTT SSL connections on port 8883. Thank you very much for posting this library!

**Comment by icabrera29** [comment]
Thank you very much

**Comment by ilgarbenli** [comment]
I couldn't POST json request to googleapis.com would anybody done this before?

**Comment by nh-ee** [comment]
I was trying to use this lib to connect to AWS S3 with API gateway, but no success till now. Did anyone work on such previously?

**Comment by ilgarbenli** [comment]
@vshymanskyy Some SSL connections worked for me with this library: github.com/govorox/SSLClient

**Comment by NavyaDevB** [comment]
> I'm working on a project using the LiliGO T-SIM7000G board. Using the native functions of TinyGSM to conectar using SSL (TINY_GSM_MODEM_SIM7000SSL), despite not having any error during compilation, in my case the connections do not work. I tryed some exemples with https and mqtt. With the library you posted, everything worked perfectly defining the modem as TINY_GSM_MODEM_SIM7000. Both HTTPS and MQTT SSL connections on port 8883. Thank you very much for posting this library!

>>>>>>>>>> 

> Hi @Kromtar!
> Can you tell me the code flow and libraries used to connect TTGO SIM7000G ESP32 Wrover-E to AWS i.e., with certificates using MQTT.
 
I have been trying for so many days, but I am getting many errors and I am unable to connected to AWS IoT core. It is reporting as MQTT connection failed, rc: -2
