### ISSUE TITLE
why there is no one response to our problem

### ISSUE THREAD

**Issue by MahmoudMohamedAli** [vshymanskyy/TinyGSM#605]
DELETED

**Comment by star297** [comment]
Bad language perhaps? My mum said she would wash my mouth out with soap and water if I spoke like that, well actually not as bad as your comments tbh.

You have to understand that contributors to this project earn no money from this and are trying to help EVERYONE by sharing their hard work.
  
Perhaps Mr. MohamedMahmoudAliPonjabiKebab would like to write his own GSM library then we could add some comments about his work.

**Comment by MahmoudMohamedAli** [comment]
OKAY,CAN I THEN TALK TO YOUR MOTHER TO TAKE DATE from her please give me her number. I promise i will try to forget her the world dude

**Comment by MahmoudMohamedAli** [comment]
i'm still waiting her number dude!i promise you again i will make her dive in milk

**Comment by SRGDamia1** [comment]
@star297 Thank you.
