### ISSUE TITLE
Loop in loop() causing Soft WDT reset

### ISSUE THREAD

**Issue by alpertandogan** [vshymanskyy/TinyGSM#64]
Hi 

Line number 564 of TinyGsmClientA6.h ...
This line make SWD reset my NodeMcu .I changed it and works well for me.
Best regards

orj 
  while (!stream.available()) {}
modified 
  while (!stream.available()) {TINY_GSM_YIELD()}

**Comment by vshymanskyy** [comment]
Thanks!

**Comment by vshymanskyy** [comment]
Fixed, will be available in next release
