### ISSUE TITLE
Not working on ESP32!

### ISSUE THREAD

**Issue by tusharvb19** [vshymanskyy/TinyGSM#68]
Even the AT debug sketch is not receiving output!
Need help.

**Comment by vshymanskyy** [comment]
Could you try with the latest master branch?

**Comment by vshymanskyy** [comment]
Which exactly hardware/modem do you use? If the issue persists, please reopen issue and specify all the details. Thank you.

**Comment by vshymanskyy** [comment]
Also, can you confirm that serial on your ESP32 is working at all, i.e, you can issue AT commands?

**Comment by tusharvb19** [comment]
I was able to test AT commands using hardware serial port and have successfully tested FONA library.
But when I tried TinyGSM even the AT Debug sketch was not working!

**Comment by tusharvb19** [comment]
Will test with the latest branch.

**Comment by 0x1abin** [comment]
i have same problem, not working in esp32.

**Comment by vshymanskyy** [comment]
Just "not working" is not an issue report. @0x1abin , what is you hardware, what sketches did you run an what's the output.

**Comment by vshymanskyy** [comment]
@0x1abin sorry I now realized that you created a separate issue.
