### ISSUE TITLE
A6

### ISSUE THREAD

**Issue by spa-sam** [vshymanskyy/TinyGSM#7]
Very cool! I hope that support for the A6 too? Thank you for the work done!

**Comment by vshymanskyy** [comment]
Yes, especially if someone helps porting it ;) Shouldn't be hard but requires 4-5 hours of tinkering.
I currently don't have neither time not the hardware to start with :(

**Comment by spa-sam** [comment]
Unfortunately not much programming experience, just learning. I can send unit in Ukraine.
К сожалению не так много опыта в программировании, только учусь. Могу отправить модуль, по Украине.

**Comment by vshymanskyy** [comment]
No thanks, I'll get mine soon. Time is much more critical ;)

**Comment by vshymanskyy** [comment]
Basic A6 support is implemented.
More testing is needed, and community support in bugfixing, improving stability is very welcome... ;)
