### ISSUE TITLE
[A6] Add modem.poweroff()

### ISSUE THREAD

**Issue by micw** [vshymanskyy/TinyGSM#70]
The GSM A6 supports power-off via at:
Command: AT+CPOF
Possible Response AT+CPOF +CPOF: MS OFF
OK
[Device will be switched off (power down mode) ]

It would be great, if you can add this. As a workaround, I send it directly to serial console.

**Comment by vshymanskyy** [comment]
I'll take a look, thank you!

**Comment by vshymanskyy** [comment]
poweroff() was added

**Comment by likewwddaa** [comment]
can we power on the modem?

**Comment by vshymanskyy** [comment]
You have to trigger power/reset pins.
