### ISSUE TITLE
Is TINY_GSM_MODEM_SIM7600 not supporting wifi connection?

### ISSUE THREAD

**Issue by JohnnyLiu2886** [vshymanskyy/TinyGSM#784]
I am using LILYGO T-SIM7600G, a controller combined with T-SIM7600G and ESP32. I am able to get network from sim card using "modem.simUnlock(GSM_PIN)".

However, when I am trying to use "modem.networkConnect(wifiSSID, wifiPass)", I got "error: 'TinyGsm' {aka 'class TinyGsmSim7600'} has no member named 'networkConnect'; did you mean 'isNetworkConnected'?".

Does it mean this library is not supporting SIM7600G with wifi connection? Is it a software issue or a hardware issue? If that is a software issue, I would solve the problem by using wifi.h instead of TinyGSM.

**Comment by Gelemikke** [comment]
SIM7600 is an LTE modem only https://www.simcom.com/product/SIM7600X.html and does not support Wi-Fi connections. If you want to use Wi-Fi on your board you are correct to be using wifi.h or other esp32 specific libraries.
