### ISSUE TITLE
QOS 1 and 2

### ISSUE THREAD

**Issue by shubhamsharmaa001** [vshymanskyy/TinyGSM#83]
I really appreciate your work.It helps me a lot.But please implement qos1 and qos2 features of MQTT

**Comment by vshymanskyy** [comment]
How is this related to TinyGSM library?

**Comment by shubhamsharmaa001** [comment]
It is an MQTT protocol feature and this library supports only quality of service 0 for publishing data.

**Comment by shubhamsharmaa001** [comment]
Sorry, I forget that you are using pubsubclient library for MQTT.
