### ISSUE TITLE
Re-structure into a super-class more uniform interface

### ISSUE THREAD

**Issue by SRGDamia1** [vshymanskyy/TinyGSM#85]
I think setting up another super-class within the "common" file would help to maintain a more uniform interface and decrease the amount of re-writing between the other files.

**Comment by vshymanskyy** [comment]
@SRGDamia1 it might be a good idea, but in general, we have lot's of small differences in the behavior of each module, and currently it's easier to just compare the whole implementation, rather than thinking what is common and what is specific (and how common files impact all the supported devices)
